package com.google.android.gms.internal.mlkit_vision_face_bundled;

import androidx.media3.datasource.cache.c;
import androidx.media3.extractor.ts.TsExtractor;
import com.google.android.gms.internal.ads.AbstractC1173g;
import java.io.IOException;
import java.util.HashMap;
import u2.C2294b;
import u2.InterfaceC2295c;
import u2.InterfaceC2296d;

/* JADX INFO: loaded from: classes3.dex */
final class zzgz implements InterfaceC2295c {
    private static final C2294b zzA;
    private static final C2294b zzB;
    private static final C2294b zzC;
    private static final C2294b zzD;
    private static final C2294b zzE;
    private static final C2294b zzF;
    private static final C2294b zzG;
    private static final C2294b zzH;
    private static final C2294b zzI;
    private static final C2294b zzJ;
    private static final C2294b zzK;
    private static final C2294b zzL;
    private static final C2294b zzM;
    private static final C2294b zzN;
    private static final C2294b zzO;
    private static final C2294b zzP;
    private static final C2294b zzQ;
    private static final C2294b zzR;
    private static final C2294b zzS;
    private static final C2294b zzT;
    private static final C2294b zzU;
    private static final C2294b zzV;
    private static final C2294b zzW;
    private static final C2294b zzX;
    private static final C2294b zzY;
    private static final C2294b zzZ;
    static final zzgz zza = new zzgz();
    private static final C2294b zzaA;
    private static final C2294b zzaB;
    private static final C2294b zzaC;
    private static final C2294b zzaD;
    private static final C2294b zzaE;
    private static final C2294b zzaF;
    private static final C2294b zzaG;
    private static final C2294b zzaH;
    private static final C2294b zzaI;
    private static final C2294b zzaJ;
    private static final C2294b zzaK;
    private static final C2294b zzaL;
    private static final C2294b zzaM;
    private static final C2294b zzaN;
    private static final C2294b zzaO;
    private static final C2294b zzaP;
    private static final C2294b zzaQ;
    private static final C2294b zzaR;
    private static final C2294b zzaS;
    private static final C2294b zzaT;
    private static final C2294b zzaU;
    private static final C2294b zzaV;
    private static final C2294b zzaW;
    private static final C2294b zzaX;
    private static final C2294b zzaY;
    private static final C2294b zzaZ;
    private static final C2294b zzaa;
    private static final C2294b zzab;
    private static final C2294b zzac;
    private static final C2294b zzad;
    private static final C2294b zzae;
    private static final C2294b zzaf;
    private static final C2294b zzag;
    private static final C2294b zzah;
    private static final C2294b zzai;
    private static final C2294b zzaj;
    private static final C2294b zzak;
    private static final C2294b zzal;
    private static final C2294b zzam;
    private static final C2294b zzan;
    private static final C2294b zzao;
    private static final C2294b zzap;
    private static final C2294b zzaq;
    private static final C2294b zzar;
    private static final C2294b zzas;
    private static final C2294b zzat;
    private static final C2294b zzau;
    private static final C2294b zzav;
    private static final C2294b zzaw;
    private static final C2294b zzax;
    private static final C2294b zzay;
    private static final C2294b zzaz;
    private static final C2294b zzb;
    private static final C2294b zzba;
    private static final C2294b zzbb;
    private static final C2294b zzbc;
    private static final C2294b zzbd;
    private static final C2294b zzbe;
    private static final C2294b zzbf;
    private static final C2294b zzbg;
    private static final C2294b zzbh;
    private static final C2294b zzbi;
    private static final C2294b zzbj;
    private static final C2294b zzbk;
    private static final C2294b zzbl;
    private static final C2294b zzbm;
    private static final C2294b zzbn;
    private static final C2294b zzbo;
    private static final C2294b zzbp;
    private static final C2294b zzbq;
    private static final C2294b zzbr;
    private static final C2294b zzbs;
    private static final C2294b zzbt;
    private static final C2294b zzbu;
    private static final C2294b zzbv;
    private static final C2294b zzbw;
    private static final C2294b zzbx;
    private static final C2294b zzby;
    private static final C2294b zzc;
    private static final C2294b zzd;
    private static final C2294b zze;
    private static final C2294b zzf;
    private static final C2294b zzg;
    private static final C2294b zzh;
    private static final C2294b zzi;
    private static final C2294b zzj;
    private static final C2294b zzk;
    private static final C2294b zzl;
    private static final C2294b zzm;
    private static final C2294b zzn;
    private static final C2294b zzo;
    private static final C2294b zzp;
    private static final C2294b zzq;
    private static final C2294b zzr;
    private static final C2294b zzs;
    private static final C2294b zzt;
    private static final C2294b zzu;
    private static final C2294b zzv;
    private static final C2294b zzw;
    private static final C2294b zzx;
    private static final C2294b zzy;
    private static final C2294b zzz;

    static {
        zzbm zzbmVarM = AbstractC1173g.m(1);
        HashMap map = new HashMap();
        map.put(zzbmVarM.annotationType(), zzbmVarM);
        zzb = new C2294b("systemInfo", c.r(map));
        zzbm zzbmVarM2 = AbstractC1173g.m(2);
        HashMap map2 = new HashMap();
        map2.put(zzbmVarM2.annotationType(), zzbmVarM2);
        zzc = new C2294b("eventName", c.r(map2));
        zzbm zzbmVarM3 = AbstractC1173g.m(37);
        HashMap map3 = new HashMap();
        map3.put(zzbmVarM3.annotationType(), zzbmVarM3);
        zzd = new C2294b("isThickClient", c.r(map3));
        zzbm zzbmVarM4 = AbstractC1173g.m(61);
        HashMap map4 = new HashMap();
        map4.put(zzbmVarM4.annotationType(), zzbmVarM4);
        zze = new C2294b("clientType", c.r(map4));
        zzbm zzbmVarM5 = AbstractC1173g.m(3);
        HashMap map5 = new HashMap();
        map5.put(zzbmVarM5.annotationType(), zzbmVarM5);
        zzf = new C2294b("modelDownloadLogEvent", c.r(map5));
        zzbm zzbmVarM6 = AbstractC1173g.m(20);
        HashMap map6 = new HashMap();
        map6.put(zzbmVarM6.annotationType(), zzbmVarM6);
        zzg = new C2294b("customModelLoadLogEvent", c.r(map6));
        zzbm zzbmVarM7 = AbstractC1173g.m(4);
        HashMap map7 = new HashMap();
        map7.put(zzbmVarM7.annotationType(), zzbmVarM7);
        zzh = new C2294b("customModelInferenceLogEvent", c.r(map7));
        zzbm zzbmVarM8 = AbstractC1173g.m(29);
        HashMap map8 = new HashMap();
        map8.put(zzbmVarM8.annotationType(), zzbmVarM8);
        zzi = new C2294b("customModelCreateLogEvent", c.r(map8));
        zzbm zzbmVarM9 = AbstractC1173g.m(5);
        HashMap map9 = new HashMap();
        map9.put(zzbmVarM9.annotationType(), zzbmVarM9);
        zzj = new C2294b("onDeviceFaceDetectionLogEvent", c.r(map9));
        zzbm zzbmVarM10 = AbstractC1173g.m(59);
        HashMap map10 = new HashMap();
        map10.put(zzbmVarM10.annotationType(), zzbmVarM10);
        zzk = new C2294b("onDeviceFaceLoadLogEvent", c.r(map10));
        zzbm zzbmVarM11 = AbstractC1173g.m(6);
        HashMap map11 = new HashMap();
        map11.put(zzbmVarM11.annotationType(), zzbmVarM11);
        zzl = new C2294b("onDeviceTextDetectionLogEvent", c.r(map11));
        zzbm zzbmVarM12 = AbstractC1173g.m(79);
        HashMap map12 = new HashMap();
        map12.put(zzbmVarM12.annotationType(), zzbmVarM12);
        zzm = new C2294b("onDeviceTextDetectionLoadLogEvent", c.r(map12));
        zzbm zzbmVarM13 = AbstractC1173g.m(7);
        HashMap map13 = new HashMap();
        map13.put(zzbmVarM13.annotationType(), zzbmVarM13);
        zzn = new C2294b("onDeviceBarcodeDetectionLogEvent", c.r(map13));
        zzbm zzbmVarM14 = AbstractC1173g.m(58);
        HashMap map14 = new HashMap();
        map14.put(zzbmVarM14.annotationType(), zzbmVarM14);
        zzo = new C2294b("onDeviceBarcodeLoadLogEvent", c.r(map14));
        zzbm zzbmVarM15 = AbstractC1173g.m(48);
        HashMap map15 = new HashMap();
        map15.put(zzbmVarM15.annotationType(), zzbmVarM15);
        zzp = new C2294b("onDeviceImageLabelCreateLogEvent", c.r(map15));
        zzbm zzbmVarM16 = AbstractC1173g.m(49);
        HashMap map16 = new HashMap();
        map16.put(zzbmVarM16.annotationType(), zzbmVarM16);
        zzq = new C2294b("onDeviceImageLabelLoadLogEvent", c.r(map16));
        zzbm zzbmVarM17 = AbstractC1173g.m(18);
        HashMap map17 = new HashMap();
        map17.put(zzbmVarM17.annotationType(), zzbmVarM17);
        zzr = new C2294b("onDeviceImageLabelDetectionLogEvent", c.r(map17));
        zzbm zzbmVarM18 = AbstractC1173g.m(26);
        HashMap map18 = new HashMap();
        map18.put(zzbmVarM18.annotationType(), zzbmVarM18);
        zzs = new C2294b("onDeviceObjectCreateLogEvent", c.r(map18));
        zzbm zzbmVarM19 = AbstractC1173g.m(27);
        HashMap map19 = new HashMap();
        map19.put(zzbmVarM19.annotationType(), zzbmVarM19);
        zzt = new C2294b("onDeviceObjectLoadLogEvent", c.r(map19));
        zzbm zzbmVarM20 = AbstractC1173g.m(28);
        HashMap map20 = new HashMap();
        map20.put(zzbmVarM20.annotationType(), zzbmVarM20);
        zzu = new C2294b("onDeviceObjectInferenceLogEvent", c.r(map20));
        zzbm zzbmVarM21 = AbstractC1173g.m(44);
        HashMap map21 = new HashMap();
        map21.put(zzbmVarM21.annotationType(), zzbmVarM21);
        zzv = new C2294b("onDevicePoseDetectionLogEvent", c.r(map21));
        zzbm zzbmVarM22 = AbstractC1173g.m(45);
        HashMap map22 = new HashMap();
        map22.put(zzbmVarM22.annotationType(), zzbmVarM22);
        zzw = new C2294b("onDeviceSegmentationLogEvent", c.r(map22));
        zzbm zzbmVarM23 = AbstractC1173g.m(19);
        HashMap map23 = new HashMap();
        map23.put(zzbmVarM23.annotationType(), zzbmVarM23);
        zzx = new C2294b("onDeviceSmartReplyLogEvent", c.r(map23));
        zzbm zzbmVarM24 = AbstractC1173g.m(21);
        HashMap map24 = new HashMap();
        map24.put(zzbmVarM24.annotationType(), zzbmVarM24);
        zzy = new C2294b("onDeviceLanguageIdentificationLogEvent", c.r(map24));
        zzbm zzbmVarM25 = AbstractC1173g.m(22);
        HashMap map25 = new HashMap();
        map25.put(zzbmVarM25.annotationType(), zzbmVarM25);
        zzz = new C2294b("onDeviceTranslationLogEvent", c.r(map25));
        zzbm zzbmVarM26 = AbstractC1173g.m(8);
        HashMap map26 = new HashMap();
        map26.put(zzbmVarM26.annotationType(), zzbmVarM26);
        zzA = new C2294b("cloudFaceDetectionLogEvent", c.r(map26));
        zzbm zzbmVarM27 = AbstractC1173g.m(9);
        HashMap map27 = new HashMap();
        map27.put(zzbmVarM27.annotationType(), zzbmVarM27);
        zzB = new C2294b("cloudCropHintDetectionLogEvent", c.r(map27));
        zzbm zzbmVarM28 = AbstractC1173g.m(10);
        HashMap map28 = new HashMap();
        map28.put(zzbmVarM28.annotationType(), zzbmVarM28);
        zzC = new C2294b("cloudDocumentTextDetectionLogEvent", c.r(map28));
        zzbm zzbmVarM29 = AbstractC1173g.m(11);
        HashMap map29 = new HashMap();
        map29.put(zzbmVarM29.annotationType(), zzbmVarM29);
        zzD = new C2294b("cloudImagePropertiesDetectionLogEvent", c.r(map29));
        zzbm zzbmVarM30 = AbstractC1173g.m(12);
        HashMap map30 = new HashMap();
        map30.put(zzbmVarM30.annotationType(), zzbmVarM30);
        zzE = new C2294b("cloudImageLabelDetectionLogEvent", c.r(map30));
        zzbm zzbmVarM31 = AbstractC1173g.m(13);
        HashMap map31 = new HashMap();
        map31.put(zzbmVarM31.annotationType(), zzbmVarM31);
        zzF = new C2294b("cloudLandmarkDetectionLogEvent", c.r(map31));
        zzbm zzbmVarM32 = AbstractC1173g.m(14);
        HashMap map32 = new HashMap();
        map32.put(zzbmVarM32.annotationType(), zzbmVarM32);
        zzG = new C2294b("cloudLogoDetectionLogEvent", c.r(map32));
        zzbm zzbmVarM33 = AbstractC1173g.m(15);
        HashMap map33 = new HashMap();
        map33.put(zzbmVarM33.annotationType(), zzbmVarM33);
        zzH = new C2294b("cloudSafeSearchDetectionLogEvent", c.r(map33));
        zzbm zzbmVarM34 = AbstractC1173g.m(16);
        HashMap map34 = new HashMap();
        map34.put(zzbmVarM34.annotationType(), zzbmVarM34);
        zzI = new C2294b("cloudTextDetectionLogEvent", c.r(map34));
        zzbm zzbmVarM35 = AbstractC1173g.m(17);
        HashMap map35 = new HashMap();
        map35.put(zzbmVarM35.annotationType(), zzbmVarM35);
        zzJ = new C2294b("cloudWebSearchDetectionLogEvent", c.r(map35));
        zzbm zzbmVarM36 = AbstractC1173g.m(23);
        HashMap map36 = new HashMap();
        map36.put(zzbmVarM36.annotationType(), zzbmVarM36);
        zzK = new C2294b("automlImageLabelingCreateLogEvent", c.r(map36));
        zzbm zzbmVarM37 = AbstractC1173g.m(24);
        HashMap map37 = new HashMap();
        map37.put(zzbmVarM37.annotationType(), zzbmVarM37);
        zzL = new C2294b("automlImageLabelingLoadLogEvent", c.r(map37));
        zzbm zzbmVarM38 = AbstractC1173g.m(25);
        HashMap map38 = new HashMap();
        map38.put(zzbmVarM38.annotationType(), zzbmVarM38);
        zzM = new C2294b("automlImageLabelingInferenceLogEvent", c.r(map38));
        zzbm zzbmVarM39 = AbstractC1173g.m(39);
        HashMap map39 = new HashMap();
        map39.put(zzbmVarM39.annotationType(), zzbmVarM39);
        zzN = new C2294b("isModelDownloadedLogEvent", c.r(map39));
        zzbm zzbmVarM40 = AbstractC1173g.m(40);
        HashMap map40 = new HashMap();
        map40.put(zzbmVarM40.annotationType(), zzbmVarM40);
        zzO = new C2294b("deleteModelLogEvent", c.r(map40));
        zzbm zzbmVarM41 = AbstractC1173g.m(30);
        HashMap map41 = new HashMap();
        map41.put(zzbmVarM41.annotationType(), zzbmVarM41);
        zzP = new C2294b("aggregatedAutomlImageLabelingInferenceLogEvent", c.r(map41));
        zzbm zzbmVarM42 = AbstractC1173g.m(31);
        HashMap map42 = new HashMap();
        map42.put(zzbmVarM42.annotationType(), zzbmVarM42);
        zzQ = new C2294b("aggregatedCustomModelInferenceLogEvent", c.r(map42));
        zzbm zzbmVarM43 = AbstractC1173g.m(32);
        HashMap map43 = new HashMap();
        map43.put(zzbmVarM43.annotationType(), zzbmVarM43);
        zzR = new C2294b("aggregatedOnDeviceFaceDetectionLogEvent", c.r(map43));
        zzbm zzbmVarM44 = AbstractC1173g.m(33);
        HashMap map44 = new HashMap();
        map44.put(zzbmVarM44.annotationType(), zzbmVarM44);
        zzS = new C2294b("aggregatedOnDeviceBarcodeDetectionLogEvent", c.r(map44));
        zzbm zzbmVarM45 = AbstractC1173g.m(34);
        HashMap map45 = new HashMap();
        map45.put(zzbmVarM45.annotationType(), zzbmVarM45);
        zzT = new C2294b("aggregatedOnDeviceImageLabelDetectionLogEvent", c.r(map45));
        zzbm zzbmVarM46 = AbstractC1173g.m(35);
        HashMap map46 = new HashMap();
        map46.put(zzbmVarM46.annotationType(), zzbmVarM46);
        zzU = new C2294b("aggregatedOnDeviceObjectInferenceLogEvent", c.r(map46));
        zzbm zzbmVarM47 = AbstractC1173g.m(36);
        HashMap map47 = new HashMap();
        map47.put(zzbmVarM47.annotationType(), zzbmVarM47);
        zzV = new C2294b("aggregatedOnDeviceTextDetectionLogEvent", c.r(map47));
        zzbm zzbmVarM48 = AbstractC1173g.m(46);
        HashMap map48 = new HashMap();
        map48.put(zzbmVarM48.annotationType(), zzbmVarM48);
        zzW = new C2294b("aggregatedOnDevicePoseDetectionLogEvent", c.r(map48));
        zzbm zzbmVarM49 = AbstractC1173g.m(47);
        HashMap map49 = new HashMap();
        map49.put(zzbmVarM49.annotationType(), zzbmVarM49);
        zzX = new C2294b("aggregatedOnDeviceSegmentationLogEvent", c.r(map49));
        zzbm zzbmVarM50 = AbstractC1173g.m(69);
        HashMap map50 = new HashMap();
        map50.put(zzbmVarM50.annotationType(), zzbmVarM50);
        zzY = new C2294b("pipelineAccelerationInferenceEvents", c.r(map50));
        zzbm zzbmVarM51 = AbstractC1173g.m(42);
        HashMap map51 = new HashMap();
        map51.put(zzbmVarM51.annotationType(), zzbmVarM51);
        zzZ = new C2294b("remoteConfigLogEvent", c.r(map51));
        zzbm zzbmVarM52 = AbstractC1173g.m(50);
        HashMap map52 = new HashMap();
        map52.put(zzbmVarM52.annotationType(), zzbmVarM52);
        zzaa = new C2294b("inputImageConstructionLogEvent", c.r(map52));
        zzbm zzbmVarM53 = AbstractC1173g.m(51);
        HashMap map53 = new HashMap();
        map53.put(zzbmVarM53.annotationType(), zzbmVarM53);
        zzab = new C2294b("leakedHandleEvent", c.r(map53));
        zzbm zzbmVarM54 = AbstractC1173g.m(52);
        HashMap map54 = new HashMap();
        map54.put(zzbmVarM54.annotationType(), zzbmVarM54);
        zzac = new C2294b("cameraSourceLogEvent", c.r(map54));
        zzbm zzbmVarM55 = AbstractC1173g.m(53);
        HashMap map55 = new HashMap();
        map55.put(zzbmVarM55.annotationType(), zzbmVarM55);
        zzad = new C2294b("imageLabelOptionalModuleLogEvent", c.r(map55));
        zzbm zzbmVarM56 = AbstractC1173g.m(54);
        HashMap map56 = new HashMap();
        map56.put(zzbmVarM56.annotationType(), zzbmVarM56);
        zzae = new C2294b("languageIdentificationOptionalModuleLogEvent", c.r(map56));
        zzbm zzbmVarM57 = AbstractC1173g.m(60);
        HashMap map57 = new HashMap();
        map57.put(zzbmVarM57.annotationType(), zzbmVarM57);
        zzaf = new C2294b("faceDetectionOptionalModuleLogEvent", c.r(map57));
        zzbm zzbmVarM58 = AbstractC1173g.m(85);
        HashMap map58 = new HashMap();
        map58.put(zzbmVarM58.annotationType(), zzbmVarM58);
        zzag = new C2294b("documentDetectionOptionalModuleLogEvent", c.r(map58));
        zzbm zzbmVarM59 = AbstractC1173g.m(86);
        HashMap map59 = new HashMap();
        map59.put(zzbmVarM59.annotationType(), zzbmVarM59);
        zzah = new C2294b("documentCroppingOptionalModuleLogEvent", c.r(map59));
        zzbm zzbmVarM60 = AbstractC1173g.m(87);
        HashMap map60 = new HashMap();
        map60.put(zzbmVarM60.annotationType(), zzbmVarM60);
        zzai = new C2294b("documentEnhancementOptionalModuleLogEvent", c.r(map60));
        zzbm zzbmVarM61 = AbstractC1173g.m(55);
        HashMap map61 = new HashMap();
        map61.put(zzbmVarM61.annotationType(), zzbmVarM61);
        zzaj = new C2294b("nlClassifierOptionalModuleLogEvent", c.r(map61));
        zzbm zzbmVarM62 = AbstractC1173g.m(56);
        HashMap map62 = new HashMap();
        map62.put(zzbmVarM62.annotationType(), zzbmVarM62);
        zzak = new C2294b("nlClassifierClientLibraryLogEvent", c.r(map62));
        zzbm zzbmVarM63 = AbstractC1173g.m(57);
        HashMap map63 = new HashMap();
        map63.put(zzbmVarM63.annotationType(), zzbmVarM63);
        zzal = new C2294b("accelerationAllowlistLogEvent", c.r(map63));
        zzbm zzbmVarM64 = AbstractC1173g.m(62);
        HashMap map64 = new HashMap();
        map64.put(zzbmVarM64.annotationType(), zzbmVarM64);
        zzam = new C2294b("toxicityDetectionCreateEvent", c.r(map64));
        zzbm zzbmVarM65 = AbstractC1173g.m(63);
        HashMap map65 = new HashMap();
        map65.put(zzbmVarM65.annotationType(), zzbmVarM65);
        zzan = new C2294b("toxicityDetectionLoadEvent", c.r(map65));
        zzbm zzbmVarM66 = AbstractC1173g.m(64);
        HashMap map66 = new HashMap();
        map66.put(zzbmVarM66.annotationType(), zzbmVarM66);
        zzao = new C2294b("toxicityDetectionInferenceEvent", c.r(map66));
        zzbm zzbmVarM67 = AbstractC1173g.m(65);
        HashMap map67 = new HashMap();
        map67.put(zzbmVarM67.annotationType(), zzbmVarM67);
        zzap = new C2294b("barcodeDetectionOptionalModuleLogEvent", c.r(map67));
        zzbm zzbmVarM68 = AbstractC1173g.m(66);
        HashMap map68 = new HashMap();
        map68.put(zzbmVarM68.annotationType(), zzbmVarM68);
        zzaq = new C2294b("customImageLabelOptionalModuleLogEvent", c.r(map68));
        zzbm zzbmVarM69 = AbstractC1173g.m(67);
        HashMap map69 = new HashMap();
        map69.put(zzbmVarM69.annotationType(), zzbmVarM69);
        zzar = new C2294b("codeScannerScanApiEvent", c.r(map69));
        zzbm zzbmVarM70 = AbstractC1173g.m(68);
        HashMap map70 = new HashMap();
        map70.put(zzbmVarM70.annotationType(), zzbmVarM70);
        zzas = new C2294b("codeScannerOptionalModuleEvent", c.r(map70));
        zzbm zzbmVarM71 = AbstractC1173g.m(70);
        HashMap map71 = new HashMap();
        map71.put(zzbmVarM71.annotationType(), zzbmVarM71);
        zzat = new C2294b("onDeviceExplicitContentCreateLogEvent", c.r(map71));
        zzbm zzbmVarM72 = AbstractC1173g.m(71);
        HashMap map72 = new HashMap();
        map72.put(zzbmVarM72.annotationType(), zzbmVarM72);
        zzau = new C2294b("onDeviceExplicitContentLoadLogEvent", c.r(map72));
        zzbm zzbmVarM73 = AbstractC1173g.m(72);
        HashMap map73 = new HashMap();
        map73.put(zzbmVarM73.annotationType(), zzbmVarM73);
        zzav = new C2294b("onDeviceExplicitContentInferenceLogEvent", c.r(map73));
        zzbm zzbmVarM74 = AbstractC1173g.m(73);
        HashMap map74 = new HashMap();
        map74.put(zzbmVarM74.annotationType(), zzbmVarM74);
        zzaw = new C2294b("aggregatedOnDeviceExplicitContentLogEvent", c.r(map74));
        zzbm zzbmVarM75 = AbstractC1173g.m(74);
        HashMap map75 = new HashMap();
        map75.put(zzbmVarM75.annotationType(), zzbmVarM75);
        zzax = new C2294b("onDeviceFaceMeshCreateLogEvent", c.r(map75));
        zzbm zzbmVarM76 = AbstractC1173g.m(75);
        HashMap map76 = new HashMap();
        map76.put(zzbmVarM76.annotationType(), zzbmVarM76);
        zzay = new C2294b("onDeviceFaceMeshLoadLogEvent", c.r(map76));
        zzbm zzbmVarM77 = AbstractC1173g.m(76);
        HashMap map77 = new HashMap();
        map77.put(zzbmVarM77.annotationType(), zzbmVarM77);
        zzaz = new C2294b("onDeviceFaceMeshLogEvent", c.r(map77));
        zzbm zzbmVarM78 = AbstractC1173g.m(77);
        HashMap map78 = new HashMap();
        map78.put(zzbmVarM78.annotationType(), zzbmVarM78);
        zzaA = new C2294b("aggregatedOnDeviceFaceMeshLogEvent", c.r(map78));
        zzbm zzbmVarM79 = AbstractC1173g.m(78);
        HashMap map79 = new HashMap();
        map79.put(zzbmVarM79.annotationType(), zzbmVarM79);
        zzaB = new C2294b("smartReplyOptionalModuleLogEvent", c.r(map79));
        zzbm zzbmVarM80 = AbstractC1173g.m(80);
        HashMap map80 = new HashMap();
        map80.put(zzbmVarM80.annotationType(), zzbmVarM80);
        zzaC = new C2294b("textDetectionOptionalModuleLogEvent", c.r(map80));
        zzbm zzbmVarM81 = AbstractC1173g.m(81);
        HashMap map81 = new HashMap();
        map81.put(zzbmVarM81.annotationType(), zzbmVarM81);
        zzaD = new C2294b("onDeviceImageQualityAnalysisCreateLogEvent", c.r(map81));
        zzbm zzbmVarM82 = AbstractC1173g.m(82);
        HashMap map82 = new HashMap();
        map82.put(zzbmVarM82.annotationType(), zzbmVarM82);
        zzaE = new C2294b("onDeviceImageQualityAnalysisLoadLogEvent", c.r(map82));
        zzbm zzbmVarM83 = AbstractC1173g.m(83);
        HashMap map83 = new HashMap();
        map83.put(zzbmVarM83.annotationType(), zzbmVarM83);
        zzaF = new C2294b("onDeviceImageQualityAnalysisLogEvent", c.r(map83));
        zzbm zzbmVarM84 = AbstractC1173g.m(84);
        HashMap map84 = new HashMap();
        map84.put(zzbmVarM84.annotationType(), zzbmVarM84);
        zzaG = new C2294b("aggregatedOnDeviceImageQualityAnalysisLogEvent", c.r(map84));
        zzbm zzbmVarM85 = AbstractC1173g.m(88);
        HashMap map85 = new HashMap();
        map85.put(zzbmVarM85.annotationType(), zzbmVarM85);
        zzaH = new C2294b("imageQualityAnalysisOptionalModuleLogEvent", c.r(map85));
        zzbm zzbmVarM86 = AbstractC1173g.m(89);
        HashMap map86 = new HashMap();
        map86.put(zzbmVarM86.annotationType(), zzbmVarM86);
        zzaI = new C2294b("imageCaptioningOptionalModuleLogEvent", c.r(map86));
        zzbm zzbmVarM87 = AbstractC1173g.m(90);
        HashMap map87 = new HashMap();
        map87.put(zzbmVarM87.annotationType(), zzbmVarM87);
        zzaJ = new C2294b("onDeviceImageCaptioningCreateLogEvent", c.r(map87));
        zzbm zzbmVarM88 = AbstractC1173g.m(91);
        HashMap map88 = new HashMap();
        map88.put(zzbmVarM88.annotationType(), zzbmVarM88);
        zzaK = new C2294b("onDeviceImageCaptioningLoadLogEvent", c.r(map88));
        zzbm zzbmVarM89 = AbstractC1173g.m(92);
        HashMap map89 = new HashMap();
        map89.put(zzbmVarM89.annotationType(), zzbmVarM89);
        zzaL = new C2294b("onDeviceImageCaptioningInferenceLogEvent", c.r(map89));
        zzbm zzbmVarM90 = AbstractC1173g.m(93);
        HashMap map90 = new HashMap();
        map90.put(zzbmVarM90.annotationType(), zzbmVarM90);
        zzaM = new C2294b("aggregatedOnDeviceImageCaptioningInferenceLogEvent", c.r(map90));
        zzbm zzbmVarM91 = AbstractC1173g.m(94);
        HashMap map91 = new HashMap();
        map91.put(zzbmVarM91.annotationType(), zzbmVarM91);
        zzaN = new C2294b("onDeviceDocumentDetectionCreateLogEvent", c.r(map91));
        zzbm zzbmVarM92 = AbstractC1173g.m(95);
        HashMap map92 = new HashMap();
        map92.put(zzbmVarM92.annotationType(), zzbmVarM92);
        zzaO = new C2294b("onDeviceDocumentDetectionLoadLogEvent", c.r(map92));
        zzbm zzbmVarM93 = AbstractC1173g.m(96);
        HashMap map93 = new HashMap();
        map93.put(zzbmVarM93.annotationType(), zzbmVarM93);
        zzaP = new C2294b("onDeviceDocumentDetectionLogEvent", c.r(map93));
        zzbm zzbmVarM94 = AbstractC1173g.m(97);
        HashMap map94 = new HashMap();
        map94.put(zzbmVarM94.annotationType(), zzbmVarM94);
        zzaQ = new C2294b("aggregatedOnDeviceDocumentDetectionLogEvent", c.r(map94));
        zzbm zzbmVarM95 = AbstractC1173g.m(98);
        HashMap map95 = new HashMap();
        map95.put(zzbmVarM95.annotationType(), zzbmVarM95);
        zzaR = new C2294b("onDeviceDocumentCroppingCreateLogEvent", c.r(map95));
        zzbm zzbmVarM96 = AbstractC1173g.m(99);
        HashMap map96 = new HashMap();
        map96.put(zzbmVarM96.annotationType(), zzbmVarM96);
        zzaS = new C2294b("onDeviceDocumentCroppingLoadLogEvent", c.r(map96));
        zzbm zzbmVarM97 = AbstractC1173g.m(100);
        HashMap map97 = new HashMap();
        map97.put(zzbmVarM97.annotationType(), zzbmVarM97);
        zzaT = new C2294b("onDeviceDocumentCroppingLogEvent", c.r(map97));
        zzbm zzbmVarM98 = AbstractC1173g.m(101);
        HashMap map98 = new HashMap();
        map98.put(zzbmVarM98.annotationType(), zzbmVarM98);
        zzaU = new C2294b("aggregatedOnDeviceDocumentCroppingLogEvent", c.r(map98));
        zzbm zzbmVarM99 = AbstractC1173g.m(102);
        HashMap map99 = new HashMap();
        map99.put(zzbmVarM99.annotationType(), zzbmVarM99);
        zzaV = new C2294b("onDeviceDocumentEnhancementCreateLogEvent", c.r(map99));
        zzbm zzbmVarM100 = AbstractC1173g.m(103);
        HashMap map100 = new HashMap();
        map100.put(zzbmVarM100.annotationType(), zzbmVarM100);
        zzaW = new C2294b("onDeviceDocumentEnhancementLoadLogEvent", c.r(map100));
        zzbm zzbmVarM101 = AbstractC1173g.m(104);
        HashMap map101 = new HashMap();
        map101.put(zzbmVarM101.annotationType(), zzbmVarM101);
        zzaX = new C2294b("onDeviceDocumentEnhancementLogEvent", c.r(map101));
        zzbm zzbmVarM102 = AbstractC1173g.m(105);
        HashMap map102 = new HashMap();
        map102.put(zzbmVarM102.annotationType(), zzbmVarM102);
        zzaY = new C2294b("aggregatedOnDeviceDocumentEnhancementLogEvent", c.r(map102));
        zzbm zzbmVarM103 = AbstractC1173g.m(106);
        HashMap map103 = new HashMap();
        map103.put(zzbmVarM103.annotationType(), zzbmVarM103);
        zzaZ = new C2294b("scannerAutoZoomEvent", c.r(map103));
        zzbm zzbmVarM104 = AbstractC1173g.m(107);
        HashMap map104 = new HashMap();
        map104.put(zzbmVarM104.annotationType(), zzbmVarM104);
        zzba = new C2294b("lowLightAutoExposureComputationEvent", c.r(map104));
        zzbm zzbmVarM105 = AbstractC1173g.m(108);
        HashMap map105 = new HashMap();
        map105.put(zzbmVarM105.annotationType(), zzbmVarM105);
        zzbb = new C2294b("lowLightFrameProcessEvent", c.r(map105));
        zzbm zzbmVarM106 = AbstractC1173g.m(109);
        HashMap map106 = new HashMap();
        map106.put(zzbmVarM106.annotationType(), zzbmVarM106);
        zzbc = new C2294b("lowLightSceneDetectionEvent", c.r(map106));
        zzbm zzbmVarM107 = AbstractC1173g.m(110);
        HashMap map107 = new HashMap();
        map107.put(zzbmVarM107.annotationType(), zzbmVarM107);
        zzbd = new C2294b("onDeviceStainRemovalLogEvent", c.r(map107));
        zzbm zzbmVarM108 = AbstractC1173g.m(111);
        HashMap map108 = new HashMap();
        map108.put(zzbmVarM108.annotationType(), zzbmVarM108);
        zzbe = new C2294b("aggregatedOnDeviceStainRemovalLogEvent", c.r(map108));
        zzbf = AbstractC1173g.D(112, C2294b.a("stainRemovalOptionalModuleLogEvent"));
        zzbg = AbstractC1173g.D(113, C2294b.a("onDeviceShadowRemovalLogEvent"));
        zzbh = AbstractC1173g.D(114, C2294b.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        zzbi = AbstractC1173g.D(115, C2294b.a("shadowRemovalOptionalModuleLogEvent"));
        zzbj = AbstractC1173g.D(116, C2294b.a("onDeviceDigitalInkSegmentationLogEvent"));
        zzbk = AbstractC1173g.D(117, C2294b.a("onDeviceDocumentScannerStartLogEvent"));
        zzbl = AbstractC1173g.D(118, C2294b.a("onDeviceDocumentScannerFinishLogEvent"));
        zzbm = AbstractC1173g.D(119, C2294b.a("onDeviceDocumentScannerUiStartLogEvent"));
        zzbn = AbstractC1173g.D(120, C2294b.a("onDeviceDocumentScannerUiFinishLogEvent"));
        zzbo = AbstractC1173g.D(121, C2294b.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        zzbp = AbstractC1173g.D(122, C2294b.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        zzbq = AbstractC1173g.D(123, C2294b.a("onDeviceDocumentScannerUiCreateLogEvent"));
        zzbr = AbstractC1173g.D(124, C2294b.a("onDeviceSubjectSegmentationCreateLogEvent"));
        zzbs = AbstractC1173g.D(125, C2294b.a("onDeviceSubjectSegmentationLoadLogEvent"));
        zzbt = AbstractC1173g.D(126, C2294b.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        zzbu = AbstractC1173g.D(127, C2294b.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        zzbv = AbstractC1173g.D(128, C2294b.a("subjectSegmentationOptionalModuleLogEvent"));
        zzbw = AbstractC1173g.D(TsExtractor.TS_STREAM_TYPE_AC3, C2294b.a("documentScannerUiModuleScreenViewEvent"));
        zzbx = AbstractC1173g.D(130, C2294b.a("documentScannerUiModuleScreenClickEvent"));
        zzby = AbstractC1173g.D(131, C2294b.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private zzgz() {
    }

    @Override // u2.InterfaceC2293a
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zznk zznkVar = (zznk) obj;
        InterfaceC2296d interfaceC2296d = (InterfaceC2296d) obj2;
        interfaceC2296d.add(zzb, zznkVar.zzd());
        interfaceC2296d.add(zzc, zznkVar.zzc());
        interfaceC2296d.add(zzd, (Object) null);
        interfaceC2296d.add(zze, zznkVar.zzb());
        interfaceC2296d.add(zzf, (Object) null);
        interfaceC2296d.add(zzg, (Object) null);
        interfaceC2296d.add(zzh, (Object) null);
        interfaceC2296d.add(zzi, (Object) null);
        interfaceC2296d.add(zzj, (Object) null);
        interfaceC2296d.add(zzk, (Object) null);
        interfaceC2296d.add(zzl, (Object) null);
        interfaceC2296d.add(zzm, (Object) null);
        interfaceC2296d.add(zzn, (Object) null);
        interfaceC2296d.add(zzo, (Object) null);
        interfaceC2296d.add(zzp, (Object) null);
        interfaceC2296d.add(zzq, (Object) null);
        interfaceC2296d.add(zzr, (Object) null);
        interfaceC2296d.add(zzs, (Object) null);
        interfaceC2296d.add(zzt, (Object) null);
        interfaceC2296d.add(zzu, (Object) null);
        interfaceC2296d.add(zzv, (Object) null);
        interfaceC2296d.add(zzw, (Object) null);
        interfaceC2296d.add(zzx, (Object) null);
        interfaceC2296d.add(zzy, (Object) null);
        interfaceC2296d.add(zzz, (Object) null);
        interfaceC2296d.add(zzA, (Object) null);
        interfaceC2296d.add(zzB, (Object) null);
        interfaceC2296d.add(zzC, (Object) null);
        interfaceC2296d.add(zzD, (Object) null);
        interfaceC2296d.add(zzE, (Object) null);
        interfaceC2296d.add(zzF, (Object) null);
        interfaceC2296d.add(zzG, (Object) null);
        interfaceC2296d.add(zzH, (Object) null);
        interfaceC2296d.add(zzI, (Object) null);
        interfaceC2296d.add(zzJ, (Object) null);
        interfaceC2296d.add(zzK, (Object) null);
        interfaceC2296d.add(zzL, (Object) null);
        interfaceC2296d.add(zzM, (Object) null);
        interfaceC2296d.add(zzN, (Object) null);
        interfaceC2296d.add(zzO, (Object) null);
        interfaceC2296d.add(zzP, (Object) null);
        interfaceC2296d.add(zzQ, (Object) null);
        interfaceC2296d.add(zzR, (Object) null);
        interfaceC2296d.add(zzS, (Object) null);
        interfaceC2296d.add(zzT, (Object) null);
        interfaceC2296d.add(zzU, (Object) null);
        interfaceC2296d.add(zzV, (Object) null);
        interfaceC2296d.add(zzW, (Object) null);
        interfaceC2296d.add(zzX, (Object) null);
        interfaceC2296d.add(zzY, (Object) null);
        interfaceC2296d.add(zzZ, (Object) null);
        interfaceC2296d.add(zzaa, (Object) null);
        interfaceC2296d.add(zzab, (Object) null);
        interfaceC2296d.add(zzac, (Object) null);
        interfaceC2296d.add(zzad, (Object) null);
        interfaceC2296d.add(zzae, (Object) null);
        interfaceC2296d.add(zzaf, zznkVar.zza());
        interfaceC2296d.add(zzag, (Object) null);
        interfaceC2296d.add(zzah, (Object) null);
        interfaceC2296d.add(zzai, (Object) null);
        interfaceC2296d.add(zzaj, (Object) null);
        interfaceC2296d.add(zzak, (Object) null);
        interfaceC2296d.add(zzal, (Object) null);
        interfaceC2296d.add(zzam, (Object) null);
        interfaceC2296d.add(zzan, (Object) null);
        interfaceC2296d.add(zzao, (Object) null);
        interfaceC2296d.add(zzap, (Object) null);
        interfaceC2296d.add(zzaq, (Object) null);
        interfaceC2296d.add(zzar, (Object) null);
        interfaceC2296d.add(zzas, (Object) null);
        interfaceC2296d.add(zzat, (Object) null);
        interfaceC2296d.add(zzau, (Object) null);
        interfaceC2296d.add(zzav, (Object) null);
        interfaceC2296d.add(zzaw, (Object) null);
        interfaceC2296d.add(zzax, (Object) null);
        interfaceC2296d.add(zzay, (Object) null);
        interfaceC2296d.add(zzaz, (Object) null);
        interfaceC2296d.add(zzaA, (Object) null);
        interfaceC2296d.add(zzaB, (Object) null);
        interfaceC2296d.add(zzaC, (Object) null);
        interfaceC2296d.add(zzaD, (Object) null);
        interfaceC2296d.add(zzaE, (Object) null);
        interfaceC2296d.add(zzaF, (Object) null);
        interfaceC2296d.add(zzaG, (Object) null);
        interfaceC2296d.add(zzaH, (Object) null);
        interfaceC2296d.add(zzaI, (Object) null);
        interfaceC2296d.add(zzaJ, (Object) null);
        interfaceC2296d.add(zzaK, (Object) null);
        interfaceC2296d.add(zzaL, (Object) null);
        interfaceC2296d.add(zzaM, (Object) null);
        interfaceC2296d.add(zzaN, (Object) null);
        interfaceC2296d.add(zzaO, (Object) null);
        interfaceC2296d.add(zzaP, (Object) null);
        interfaceC2296d.add(zzaQ, (Object) null);
        interfaceC2296d.add(zzaR, (Object) null);
        interfaceC2296d.add(zzaS, (Object) null);
        interfaceC2296d.add(zzaT, (Object) null);
        interfaceC2296d.add(zzaU, (Object) null);
        interfaceC2296d.add(zzaV, (Object) null);
        interfaceC2296d.add(zzaW, (Object) null);
        interfaceC2296d.add(zzaX, (Object) null);
        interfaceC2296d.add(zzaY, (Object) null);
        interfaceC2296d.add(zzaZ, (Object) null);
        interfaceC2296d.add(zzba, (Object) null);
        interfaceC2296d.add(zzbb, (Object) null);
        interfaceC2296d.add(zzbc, (Object) null);
        interfaceC2296d.add(zzbd, (Object) null);
        interfaceC2296d.add(zzbe, (Object) null);
        interfaceC2296d.add(zzbf, (Object) null);
        interfaceC2296d.add(zzbg, (Object) null);
        interfaceC2296d.add(zzbh, (Object) null);
        interfaceC2296d.add(zzbi, (Object) null);
        interfaceC2296d.add(zzbj, (Object) null);
        interfaceC2296d.add(zzbk, (Object) null);
        interfaceC2296d.add(zzbl, (Object) null);
        interfaceC2296d.add(zzbm, (Object) null);
        interfaceC2296d.add(zzbn, (Object) null);
        interfaceC2296d.add(zzbo, (Object) null);
        interfaceC2296d.add(zzbp, (Object) null);
        interfaceC2296d.add(zzbq, (Object) null);
        interfaceC2296d.add(zzbr, (Object) null);
        interfaceC2296d.add(zzbs, (Object) null);
        interfaceC2296d.add(zzbt, (Object) null);
        interfaceC2296d.add(zzbu, (Object) null);
        interfaceC2296d.add(zzbv, (Object) null);
        interfaceC2296d.add(zzbw, (Object) null);
        interfaceC2296d.add(zzbx, (Object) null);
        interfaceC2296d.add(zzby, (Object) null);
    }
}
