package com.google.android.gms.internal.mlkit_common;

import androidx.media3.datasource.cache.c;
import androidx.media3.extractor.ts.TsExtractor;
import com.google.android.gms.internal.ads.AbstractC1173g;
import java.io.IOException;
import java.util.HashMap;
import u2.C2294b;
import u2.InterfaceC2295c;
import u2.InterfaceC2296d;

/* JADX INFO: loaded from: classes3.dex */
final class zzgp implements InterfaceC2295c {
    private static final C2294b zzA;
    private static final C2294b zzB;
    private static final C2294b zzC;
    private static final C2294b zzD;
    private static final C2294b zzE;
    private static final C2294b zzF;
    private static final C2294b zzG;
    private static final C2294b zzH;
    private static final C2294b zzI;
    private static final C2294b zzJ;
    private static final C2294b zzK;
    private static final C2294b zzL;
    private static final C2294b zzM;
    private static final C2294b zzN;
    private static final C2294b zzO;
    private static final C2294b zzP;
    private static final C2294b zzQ;
    private static final C2294b zzR;
    private static final C2294b zzS;
    private static final C2294b zzT;
    private static final C2294b zzU;
    private static final C2294b zzV;
    private static final C2294b zzW;
    private static final C2294b zzX;
    private static final C2294b zzY;
    private static final C2294b zzZ;
    static final zzgp zza = new zzgp();
    private static final C2294b zzaA;
    private static final C2294b zzaB;
    private static final C2294b zzaC;
    private static final C2294b zzaD;
    private static final C2294b zzaE;
    private static final C2294b zzaF;
    private static final C2294b zzaG;
    private static final C2294b zzaH;
    private static final C2294b zzaI;
    private static final C2294b zzaJ;
    private static final C2294b zzaK;
    private static final C2294b zzaL;
    private static final C2294b zzaM;
    private static final C2294b zzaN;
    private static final C2294b zzaO;
    private static final C2294b zzaP;
    private static final C2294b zzaQ;
    private static final C2294b zzaR;
    private static final C2294b zzaS;
    private static final C2294b zzaT;
    private static final C2294b zzaU;
    private static final C2294b zzaV;
    private static final C2294b zzaW;
    private static final C2294b zzaX;
    private static final C2294b zzaY;
    private static final C2294b zzaZ;
    private static final C2294b zzaa;
    private static final C2294b zzab;
    private static final C2294b zzac;
    private static final C2294b zzad;
    private static final C2294b zzae;
    private static final C2294b zzaf;
    private static final C2294b zzag;
    private static final C2294b zzah;
    private static final C2294b zzai;
    private static final C2294b zzaj;
    private static final C2294b zzak;
    private static final C2294b zzal;
    private static final C2294b zzam;
    private static final C2294b zzan;
    private static final C2294b zzao;
    private static final C2294b zzap;
    private static final C2294b zzaq;
    private static final C2294b zzar;
    private static final C2294b zzas;
    private static final C2294b zzat;
    private static final C2294b zzau;
    private static final C2294b zzav;
    private static final C2294b zzaw;
    private static final C2294b zzax;
    private static final C2294b zzay;
    private static final C2294b zzaz;
    private static final C2294b zzb;
    private static final C2294b zzba;
    private static final C2294b zzbb;
    private static final C2294b zzbc;
    private static final C2294b zzbd;
    private static final C2294b zzbe;
    private static final C2294b zzbf;
    private static final C2294b zzbg;
    private static final C2294b zzbh;
    private static final C2294b zzbi;
    private static final C2294b zzbj;
    private static final C2294b zzbk;
    private static final C2294b zzbl;
    private static final C2294b zzbm;
    private static final C2294b zzbn;
    private static final C2294b zzbo;
    private static final C2294b zzbp;
    private static final C2294b zzbq;
    private static final C2294b zzbr;
    private static final C2294b zzbs;
    private static final C2294b zzbt;
    private static final C2294b zzbu;
    private static final C2294b zzbv;
    private static final C2294b zzbw;
    private static final C2294b zzbx;
    private static final C2294b zzby;
    private static final C2294b zzc;
    private static final C2294b zzd;
    private static final C2294b zze;
    private static final C2294b zzf;
    private static final C2294b zzg;
    private static final C2294b zzh;
    private static final C2294b zzi;
    private static final C2294b zzj;
    private static final C2294b zzk;
    private static final C2294b zzl;
    private static final C2294b zzm;
    private static final C2294b zzn;
    private static final C2294b zzo;
    private static final C2294b zzp;
    private static final C2294b zzq;
    private static final C2294b zzr;
    private static final C2294b zzs;
    private static final C2294b zzt;
    private static final C2294b zzu;
    private static final C2294b zzv;
    private static final C2294b zzw;
    private static final C2294b zzx;
    private static final C2294b zzy;
    private static final C2294b zzz;

    static {
        zzbc zzbcVarG = AbstractC1173g.g(1);
        HashMap map = new HashMap();
        map.put(zzbcVarG.annotationType(), zzbcVarG);
        zzb = new C2294b("systemInfo", c.r(map));
        zzbc zzbcVarG2 = AbstractC1173g.g(2);
        HashMap map2 = new HashMap();
        map2.put(zzbcVarG2.annotationType(), zzbcVarG2);
        zzc = new C2294b("eventName", c.r(map2));
        zzbc zzbcVarG3 = AbstractC1173g.g(37);
        HashMap map3 = new HashMap();
        map3.put(zzbcVarG3.annotationType(), zzbcVarG3);
        zzd = new C2294b("isThickClient", c.r(map3));
        zzbc zzbcVarG4 = AbstractC1173g.g(61);
        HashMap map4 = new HashMap();
        map4.put(zzbcVarG4.annotationType(), zzbcVarG4);
        zze = new C2294b("clientType", c.r(map4));
        zzbc zzbcVarG5 = AbstractC1173g.g(3);
        HashMap map5 = new HashMap();
        map5.put(zzbcVarG5.annotationType(), zzbcVarG5);
        zzf = new C2294b("modelDownloadLogEvent", c.r(map5));
        zzbc zzbcVarG6 = AbstractC1173g.g(20);
        HashMap map6 = new HashMap();
        map6.put(zzbcVarG6.annotationType(), zzbcVarG6);
        zzg = new C2294b("customModelLoadLogEvent", c.r(map6));
        zzbc zzbcVarG7 = AbstractC1173g.g(4);
        HashMap map7 = new HashMap();
        map7.put(zzbcVarG7.annotationType(), zzbcVarG7);
        zzh = new C2294b("customModelInferenceLogEvent", c.r(map7));
        zzbc zzbcVarG8 = AbstractC1173g.g(29);
        HashMap map8 = new HashMap();
        map8.put(zzbcVarG8.annotationType(), zzbcVarG8);
        zzi = new C2294b("customModelCreateLogEvent", c.r(map8));
        zzbc zzbcVarG9 = AbstractC1173g.g(5);
        HashMap map9 = new HashMap();
        map9.put(zzbcVarG9.annotationType(), zzbcVarG9);
        zzj = new C2294b("onDeviceFaceDetectionLogEvent", c.r(map9));
        zzbc zzbcVarG10 = AbstractC1173g.g(59);
        HashMap map10 = new HashMap();
        map10.put(zzbcVarG10.annotationType(), zzbcVarG10);
        zzk = new C2294b("onDeviceFaceLoadLogEvent", c.r(map10));
        zzbc zzbcVarG11 = AbstractC1173g.g(6);
        HashMap map11 = new HashMap();
        map11.put(zzbcVarG11.annotationType(), zzbcVarG11);
        zzl = new C2294b("onDeviceTextDetectionLogEvent", c.r(map11));
        zzbc zzbcVarG12 = AbstractC1173g.g(79);
        HashMap map12 = new HashMap();
        map12.put(zzbcVarG12.annotationType(), zzbcVarG12);
        zzm = new C2294b("onDeviceTextDetectionLoadLogEvent", c.r(map12));
        zzbc zzbcVarG13 = AbstractC1173g.g(7);
        HashMap map13 = new HashMap();
        map13.put(zzbcVarG13.annotationType(), zzbcVarG13);
        zzn = new C2294b("onDeviceBarcodeDetectionLogEvent", c.r(map13));
        zzbc zzbcVarG14 = AbstractC1173g.g(58);
        HashMap map14 = new HashMap();
        map14.put(zzbcVarG14.annotationType(), zzbcVarG14);
        zzo = new C2294b("onDeviceBarcodeLoadLogEvent", c.r(map14));
        zzbc zzbcVarG15 = AbstractC1173g.g(48);
        HashMap map15 = new HashMap();
        map15.put(zzbcVarG15.annotationType(), zzbcVarG15);
        zzp = new C2294b("onDeviceImageLabelCreateLogEvent", c.r(map15));
        zzbc zzbcVarG16 = AbstractC1173g.g(49);
        HashMap map16 = new HashMap();
        map16.put(zzbcVarG16.annotationType(), zzbcVarG16);
        zzq = new C2294b("onDeviceImageLabelLoadLogEvent", c.r(map16));
        zzbc zzbcVarG17 = AbstractC1173g.g(18);
        HashMap map17 = new HashMap();
        map17.put(zzbcVarG17.annotationType(), zzbcVarG17);
        zzr = new C2294b("onDeviceImageLabelDetectionLogEvent", c.r(map17));
        zzbc zzbcVarG18 = AbstractC1173g.g(26);
        HashMap map18 = new HashMap();
        map18.put(zzbcVarG18.annotationType(), zzbcVarG18);
        zzs = new C2294b("onDeviceObjectCreateLogEvent", c.r(map18));
        zzbc zzbcVarG19 = AbstractC1173g.g(27);
        HashMap map19 = new HashMap();
        map19.put(zzbcVarG19.annotationType(), zzbcVarG19);
        zzt = new C2294b("onDeviceObjectLoadLogEvent", c.r(map19));
        zzbc zzbcVarG20 = AbstractC1173g.g(28);
        HashMap map20 = new HashMap();
        map20.put(zzbcVarG20.annotationType(), zzbcVarG20);
        zzu = new C2294b("onDeviceObjectInferenceLogEvent", c.r(map20));
        zzbc zzbcVarG21 = AbstractC1173g.g(44);
        HashMap map21 = new HashMap();
        map21.put(zzbcVarG21.annotationType(), zzbcVarG21);
        zzv = new C2294b("onDevicePoseDetectionLogEvent", c.r(map21));
        zzbc zzbcVarG22 = AbstractC1173g.g(45);
        HashMap map22 = new HashMap();
        map22.put(zzbcVarG22.annotationType(), zzbcVarG22);
        zzw = new C2294b("onDeviceSegmentationLogEvent", c.r(map22));
        zzbc zzbcVarG23 = AbstractC1173g.g(19);
        HashMap map23 = new HashMap();
        map23.put(zzbcVarG23.annotationType(), zzbcVarG23);
        zzx = new C2294b("onDeviceSmartReplyLogEvent", c.r(map23));
        zzbc zzbcVarG24 = AbstractC1173g.g(21);
        HashMap map24 = new HashMap();
        map24.put(zzbcVarG24.annotationType(), zzbcVarG24);
        zzy = new C2294b("onDeviceLanguageIdentificationLogEvent", c.r(map24));
        zzbc zzbcVarG25 = AbstractC1173g.g(22);
        HashMap map25 = new HashMap();
        map25.put(zzbcVarG25.annotationType(), zzbcVarG25);
        zzz = new C2294b("onDeviceTranslationLogEvent", c.r(map25));
        zzbc zzbcVarG26 = AbstractC1173g.g(8);
        HashMap map26 = new HashMap();
        map26.put(zzbcVarG26.annotationType(), zzbcVarG26);
        zzA = new C2294b("cloudFaceDetectionLogEvent", c.r(map26));
        zzbc zzbcVarG27 = AbstractC1173g.g(9);
        HashMap map27 = new HashMap();
        map27.put(zzbcVarG27.annotationType(), zzbcVarG27);
        zzB = new C2294b("cloudCropHintDetectionLogEvent", c.r(map27));
        zzbc zzbcVarG28 = AbstractC1173g.g(10);
        HashMap map28 = new HashMap();
        map28.put(zzbcVarG28.annotationType(), zzbcVarG28);
        zzC = new C2294b("cloudDocumentTextDetectionLogEvent", c.r(map28));
        zzbc zzbcVarG29 = AbstractC1173g.g(11);
        HashMap map29 = new HashMap();
        map29.put(zzbcVarG29.annotationType(), zzbcVarG29);
        zzD = new C2294b("cloudImagePropertiesDetectionLogEvent", c.r(map29));
        zzbc zzbcVarG30 = AbstractC1173g.g(12);
        HashMap map30 = new HashMap();
        map30.put(zzbcVarG30.annotationType(), zzbcVarG30);
        zzE = new C2294b("cloudImageLabelDetectionLogEvent", c.r(map30));
        zzbc zzbcVarG31 = AbstractC1173g.g(13);
        HashMap map31 = new HashMap();
        map31.put(zzbcVarG31.annotationType(), zzbcVarG31);
        zzF = new C2294b("cloudLandmarkDetectionLogEvent", c.r(map31));
        zzbc zzbcVarG32 = AbstractC1173g.g(14);
        HashMap map32 = new HashMap();
        map32.put(zzbcVarG32.annotationType(), zzbcVarG32);
        zzG = new C2294b("cloudLogoDetectionLogEvent", c.r(map32));
        zzbc zzbcVarG33 = AbstractC1173g.g(15);
        HashMap map33 = new HashMap();
        map33.put(zzbcVarG33.annotationType(), zzbcVarG33);
        zzH = new C2294b("cloudSafeSearchDetectionLogEvent", c.r(map33));
        zzbc zzbcVarG34 = AbstractC1173g.g(16);
        HashMap map34 = new HashMap();
        map34.put(zzbcVarG34.annotationType(), zzbcVarG34);
        zzI = new C2294b("cloudTextDetectionLogEvent", c.r(map34));
        zzbc zzbcVarG35 = AbstractC1173g.g(17);
        HashMap map35 = new HashMap();
        map35.put(zzbcVarG35.annotationType(), zzbcVarG35);
        zzJ = new C2294b("cloudWebSearchDetectionLogEvent", c.r(map35));
        zzbc zzbcVarG36 = AbstractC1173g.g(23);
        HashMap map36 = new HashMap();
        map36.put(zzbcVarG36.annotationType(), zzbcVarG36);
        zzK = new C2294b("automlImageLabelingCreateLogEvent", c.r(map36));
        zzbc zzbcVarG37 = AbstractC1173g.g(24);
        HashMap map37 = new HashMap();
        map37.put(zzbcVarG37.annotationType(), zzbcVarG37);
        zzL = new C2294b("automlImageLabelingLoadLogEvent", c.r(map37));
        zzbc zzbcVarG38 = AbstractC1173g.g(25);
        HashMap map38 = new HashMap();
        map38.put(zzbcVarG38.annotationType(), zzbcVarG38);
        zzM = new C2294b("automlImageLabelingInferenceLogEvent", c.r(map38));
        zzbc zzbcVarG39 = AbstractC1173g.g(39);
        HashMap map39 = new HashMap();
        map39.put(zzbcVarG39.annotationType(), zzbcVarG39);
        zzN = new C2294b("isModelDownloadedLogEvent", c.r(map39));
        zzbc zzbcVarG40 = AbstractC1173g.g(40);
        HashMap map40 = new HashMap();
        map40.put(zzbcVarG40.annotationType(), zzbcVarG40);
        zzO = new C2294b("deleteModelLogEvent", c.r(map40));
        zzbc zzbcVarG41 = AbstractC1173g.g(30);
        HashMap map41 = new HashMap();
        map41.put(zzbcVarG41.annotationType(), zzbcVarG41);
        zzP = new C2294b("aggregatedAutomlImageLabelingInferenceLogEvent", c.r(map41));
        zzbc zzbcVarG42 = AbstractC1173g.g(31);
        HashMap map42 = new HashMap();
        map42.put(zzbcVarG42.annotationType(), zzbcVarG42);
        zzQ = new C2294b("aggregatedCustomModelInferenceLogEvent", c.r(map42));
        zzbc zzbcVarG43 = AbstractC1173g.g(32);
        HashMap map43 = new HashMap();
        map43.put(zzbcVarG43.annotationType(), zzbcVarG43);
        zzR = new C2294b("aggregatedOnDeviceFaceDetectionLogEvent", c.r(map43));
        zzbc zzbcVarG44 = AbstractC1173g.g(33);
        HashMap map44 = new HashMap();
        map44.put(zzbcVarG44.annotationType(), zzbcVarG44);
        zzS = new C2294b("aggregatedOnDeviceBarcodeDetectionLogEvent", c.r(map44));
        zzbc zzbcVarG45 = AbstractC1173g.g(34);
        HashMap map45 = new HashMap();
        map45.put(zzbcVarG45.annotationType(), zzbcVarG45);
        zzT = new C2294b("aggregatedOnDeviceImageLabelDetectionLogEvent", c.r(map45));
        zzbc zzbcVarG46 = AbstractC1173g.g(35);
        HashMap map46 = new HashMap();
        map46.put(zzbcVarG46.annotationType(), zzbcVarG46);
        zzU = new C2294b("aggregatedOnDeviceObjectInferenceLogEvent", c.r(map46));
        zzbc zzbcVarG47 = AbstractC1173g.g(36);
        HashMap map47 = new HashMap();
        map47.put(zzbcVarG47.annotationType(), zzbcVarG47);
        zzV = new C2294b("aggregatedOnDeviceTextDetectionLogEvent", c.r(map47));
        zzbc zzbcVarG48 = AbstractC1173g.g(46);
        HashMap map48 = new HashMap();
        map48.put(zzbcVarG48.annotationType(), zzbcVarG48);
        zzW = new C2294b("aggregatedOnDevicePoseDetectionLogEvent", c.r(map48));
        zzbc zzbcVarG49 = AbstractC1173g.g(47);
        HashMap map49 = new HashMap();
        map49.put(zzbcVarG49.annotationType(), zzbcVarG49);
        zzX = new C2294b("aggregatedOnDeviceSegmentationLogEvent", c.r(map49));
        zzbc zzbcVarG50 = AbstractC1173g.g(69);
        HashMap map50 = new HashMap();
        map50.put(zzbcVarG50.annotationType(), zzbcVarG50);
        zzY = new C2294b("pipelineAccelerationInferenceEvents", c.r(map50));
        zzbc zzbcVarG51 = AbstractC1173g.g(42);
        HashMap map51 = new HashMap();
        map51.put(zzbcVarG51.annotationType(), zzbcVarG51);
        zzZ = new C2294b("remoteConfigLogEvent", c.r(map51));
        zzbc zzbcVarG52 = AbstractC1173g.g(50);
        HashMap map52 = new HashMap();
        map52.put(zzbcVarG52.annotationType(), zzbcVarG52);
        zzaa = new C2294b("inputImageConstructionLogEvent", c.r(map52));
        zzbc zzbcVarG53 = AbstractC1173g.g(51);
        HashMap map53 = new HashMap();
        map53.put(zzbcVarG53.annotationType(), zzbcVarG53);
        zzab = new C2294b("leakedHandleEvent", c.r(map53));
        zzbc zzbcVarG54 = AbstractC1173g.g(52);
        HashMap map54 = new HashMap();
        map54.put(zzbcVarG54.annotationType(), zzbcVarG54);
        zzac = new C2294b("cameraSourceLogEvent", c.r(map54));
        zzbc zzbcVarG55 = AbstractC1173g.g(53);
        HashMap map55 = new HashMap();
        map55.put(zzbcVarG55.annotationType(), zzbcVarG55);
        zzad = new C2294b("imageLabelOptionalModuleLogEvent", c.r(map55));
        zzbc zzbcVarG56 = AbstractC1173g.g(54);
        HashMap map56 = new HashMap();
        map56.put(zzbcVarG56.annotationType(), zzbcVarG56);
        zzae = new C2294b("languageIdentificationOptionalModuleLogEvent", c.r(map56));
        zzbc zzbcVarG57 = AbstractC1173g.g(60);
        HashMap map57 = new HashMap();
        map57.put(zzbcVarG57.annotationType(), zzbcVarG57);
        zzaf = new C2294b("faceDetectionOptionalModuleLogEvent", c.r(map57));
        zzbc zzbcVarG58 = AbstractC1173g.g(85);
        HashMap map58 = new HashMap();
        map58.put(zzbcVarG58.annotationType(), zzbcVarG58);
        zzag = new C2294b("documentDetectionOptionalModuleLogEvent", c.r(map58));
        zzbc zzbcVarG59 = AbstractC1173g.g(86);
        HashMap map59 = new HashMap();
        map59.put(zzbcVarG59.annotationType(), zzbcVarG59);
        zzah = new C2294b("documentCroppingOptionalModuleLogEvent", c.r(map59));
        zzbc zzbcVarG60 = AbstractC1173g.g(87);
        HashMap map60 = new HashMap();
        map60.put(zzbcVarG60.annotationType(), zzbcVarG60);
        zzai = new C2294b("documentEnhancementOptionalModuleLogEvent", c.r(map60));
        zzbc zzbcVarG61 = AbstractC1173g.g(55);
        HashMap map61 = new HashMap();
        map61.put(zzbcVarG61.annotationType(), zzbcVarG61);
        zzaj = new C2294b("nlClassifierOptionalModuleLogEvent", c.r(map61));
        zzbc zzbcVarG62 = AbstractC1173g.g(56);
        HashMap map62 = new HashMap();
        map62.put(zzbcVarG62.annotationType(), zzbcVarG62);
        zzak = new C2294b("nlClassifierClientLibraryLogEvent", c.r(map62));
        zzbc zzbcVarG63 = AbstractC1173g.g(57);
        HashMap map63 = new HashMap();
        map63.put(zzbcVarG63.annotationType(), zzbcVarG63);
        zzal = new C2294b("accelerationAllowlistLogEvent", c.r(map63));
        zzbc zzbcVarG64 = AbstractC1173g.g(62);
        HashMap map64 = new HashMap();
        map64.put(zzbcVarG64.annotationType(), zzbcVarG64);
        zzam = new C2294b("toxicityDetectionCreateEvent", c.r(map64));
        zzbc zzbcVarG65 = AbstractC1173g.g(63);
        HashMap map65 = new HashMap();
        map65.put(zzbcVarG65.annotationType(), zzbcVarG65);
        zzan = new C2294b("toxicityDetectionLoadEvent", c.r(map65));
        zzbc zzbcVarG66 = AbstractC1173g.g(64);
        HashMap map66 = new HashMap();
        map66.put(zzbcVarG66.annotationType(), zzbcVarG66);
        zzao = new C2294b("toxicityDetectionInferenceEvent", c.r(map66));
        zzbc zzbcVarG67 = AbstractC1173g.g(65);
        HashMap map67 = new HashMap();
        map67.put(zzbcVarG67.annotationType(), zzbcVarG67);
        zzap = new C2294b("barcodeDetectionOptionalModuleLogEvent", c.r(map67));
        zzbc zzbcVarG68 = AbstractC1173g.g(66);
        HashMap map68 = new HashMap();
        map68.put(zzbcVarG68.annotationType(), zzbcVarG68);
        zzaq = new C2294b("customImageLabelOptionalModuleLogEvent", c.r(map68));
        zzbc zzbcVarG69 = AbstractC1173g.g(67);
        HashMap map69 = new HashMap();
        map69.put(zzbcVarG69.annotationType(), zzbcVarG69);
        zzar = new C2294b("codeScannerScanApiEvent", c.r(map69));
        zzbc zzbcVarG70 = AbstractC1173g.g(68);
        HashMap map70 = new HashMap();
        map70.put(zzbcVarG70.annotationType(), zzbcVarG70);
        zzas = new C2294b("codeScannerOptionalModuleEvent", c.r(map70));
        zzbc zzbcVarG71 = AbstractC1173g.g(70);
        HashMap map71 = new HashMap();
        map71.put(zzbcVarG71.annotationType(), zzbcVarG71);
        zzat = new C2294b("onDeviceExplicitContentCreateLogEvent", c.r(map71));
        zzbc zzbcVarG72 = AbstractC1173g.g(71);
        HashMap map72 = new HashMap();
        map72.put(zzbcVarG72.annotationType(), zzbcVarG72);
        zzau = new C2294b("onDeviceExplicitContentLoadLogEvent", c.r(map72));
        zzbc zzbcVarG73 = AbstractC1173g.g(72);
        HashMap map73 = new HashMap();
        map73.put(zzbcVarG73.annotationType(), zzbcVarG73);
        zzav = new C2294b("onDeviceExplicitContentInferenceLogEvent", c.r(map73));
        zzbc zzbcVarG74 = AbstractC1173g.g(73);
        HashMap map74 = new HashMap();
        map74.put(zzbcVarG74.annotationType(), zzbcVarG74);
        zzaw = new C2294b("aggregatedOnDeviceExplicitContentLogEvent", c.r(map74));
        zzbc zzbcVarG75 = AbstractC1173g.g(74);
        HashMap map75 = new HashMap();
        map75.put(zzbcVarG75.annotationType(), zzbcVarG75);
        zzax = new C2294b("onDeviceFaceMeshCreateLogEvent", c.r(map75));
        zzbc zzbcVarG76 = AbstractC1173g.g(75);
        HashMap map76 = new HashMap();
        map76.put(zzbcVarG76.annotationType(), zzbcVarG76);
        zzay = new C2294b("onDeviceFaceMeshLoadLogEvent", c.r(map76));
        zzbc zzbcVarG77 = AbstractC1173g.g(76);
        HashMap map77 = new HashMap();
        map77.put(zzbcVarG77.annotationType(), zzbcVarG77);
        zzaz = new C2294b("onDeviceFaceMeshLogEvent", c.r(map77));
        zzbc zzbcVarG78 = AbstractC1173g.g(77);
        HashMap map78 = new HashMap();
        map78.put(zzbcVarG78.annotationType(), zzbcVarG78);
        zzaA = new C2294b("aggregatedOnDeviceFaceMeshLogEvent", c.r(map78));
        zzbc zzbcVarG79 = AbstractC1173g.g(78);
        HashMap map79 = new HashMap();
        map79.put(zzbcVarG79.annotationType(), zzbcVarG79);
        zzaB = new C2294b("smartReplyOptionalModuleLogEvent", c.r(map79));
        zzbc zzbcVarG80 = AbstractC1173g.g(80);
        HashMap map80 = new HashMap();
        map80.put(zzbcVarG80.annotationType(), zzbcVarG80);
        zzaC = new C2294b("textDetectionOptionalModuleLogEvent", c.r(map80));
        zzbc zzbcVarG81 = AbstractC1173g.g(81);
        HashMap map81 = new HashMap();
        map81.put(zzbcVarG81.annotationType(), zzbcVarG81);
        zzaD = new C2294b("onDeviceImageQualityAnalysisCreateLogEvent", c.r(map81));
        zzbc zzbcVarG82 = AbstractC1173g.g(82);
        HashMap map82 = new HashMap();
        map82.put(zzbcVarG82.annotationType(), zzbcVarG82);
        zzaE = new C2294b("onDeviceImageQualityAnalysisLoadLogEvent", c.r(map82));
        zzbc zzbcVarG83 = AbstractC1173g.g(83);
        HashMap map83 = new HashMap();
        map83.put(zzbcVarG83.annotationType(), zzbcVarG83);
        zzaF = new C2294b("onDeviceImageQualityAnalysisLogEvent", c.r(map83));
        zzbc zzbcVarG84 = AbstractC1173g.g(84);
        HashMap map84 = new HashMap();
        map84.put(zzbcVarG84.annotationType(), zzbcVarG84);
        zzaG = new C2294b("aggregatedOnDeviceImageQualityAnalysisLogEvent", c.r(map84));
        zzbc zzbcVarG85 = AbstractC1173g.g(88);
        HashMap map85 = new HashMap();
        map85.put(zzbcVarG85.annotationType(), zzbcVarG85);
        zzaH = new C2294b("imageQualityAnalysisOptionalModuleLogEvent", c.r(map85));
        zzbc zzbcVarG86 = AbstractC1173g.g(89);
        HashMap map86 = new HashMap();
        map86.put(zzbcVarG86.annotationType(), zzbcVarG86);
        zzaI = new C2294b("imageCaptioningOptionalModuleLogEvent", c.r(map86));
        zzbc zzbcVarG87 = AbstractC1173g.g(90);
        HashMap map87 = new HashMap();
        map87.put(zzbcVarG87.annotationType(), zzbcVarG87);
        zzaJ = new C2294b("onDeviceImageCaptioningCreateLogEvent", c.r(map87));
        zzbc zzbcVarG88 = AbstractC1173g.g(91);
        HashMap map88 = new HashMap();
        map88.put(zzbcVarG88.annotationType(), zzbcVarG88);
        zzaK = new C2294b("onDeviceImageCaptioningLoadLogEvent", c.r(map88));
        zzbc zzbcVarG89 = AbstractC1173g.g(92);
        HashMap map89 = new HashMap();
        map89.put(zzbcVarG89.annotationType(), zzbcVarG89);
        zzaL = new C2294b("onDeviceImageCaptioningInferenceLogEvent", c.r(map89));
        zzbc zzbcVarG90 = AbstractC1173g.g(93);
        HashMap map90 = new HashMap();
        map90.put(zzbcVarG90.annotationType(), zzbcVarG90);
        zzaM = new C2294b("aggregatedOnDeviceImageCaptioningInferenceLogEvent", c.r(map90));
        zzbc zzbcVarG91 = AbstractC1173g.g(94);
        HashMap map91 = new HashMap();
        map91.put(zzbcVarG91.annotationType(), zzbcVarG91);
        zzaN = new C2294b("onDeviceDocumentDetectionCreateLogEvent", c.r(map91));
        zzbc zzbcVarG92 = AbstractC1173g.g(95);
        HashMap map92 = new HashMap();
        map92.put(zzbcVarG92.annotationType(), zzbcVarG92);
        zzaO = new C2294b("onDeviceDocumentDetectionLoadLogEvent", c.r(map92));
        zzbc zzbcVarG93 = AbstractC1173g.g(96);
        HashMap map93 = new HashMap();
        map93.put(zzbcVarG93.annotationType(), zzbcVarG93);
        zzaP = new C2294b("onDeviceDocumentDetectionLogEvent", c.r(map93));
        zzbc zzbcVarG94 = AbstractC1173g.g(97);
        HashMap map94 = new HashMap();
        map94.put(zzbcVarG94.annotationType(), zzbcVarG94);
        zzaQ = new C2294b("aggregatedOnDeviceDocumentDetectionLogEvent", c.r(map94));
        zzbc zzbcVarG95 = AbstractC1173g.g(98);
        HashMap map95 = new HashMap();
        map95.put(zzbcVarG95.annotationType(), zzbcVarG95);
        zzaR = new C2294b("onDeviceDocumentCroppingCreateLogEvent", c.r(map95));
        zzbc zzbcVarG96 = AbstractC1173g.g(99);
        HashMap map96 = new HashMap();
        map96.put(zzbcVarG96.annotationType(), zzbcVarG96);
        zzaS = new C2294b("onDeviceDocumentCroppingLoadLogEvent", c.r(map96));
        zzbc zzbcVarG97 = AbstractC1173g.g(100);
        HashMap map97 = new HashMap();
        map97.put(zzbcVarG97.annotationType(), zzbcVarG97);
        zzaT = new C2294b("onDeviceDocumentCroppingLogEvent", c.r(map97));
        zzbc zzbcVarG98 = AbstractC1173g.g(101);
        HashMap map98 = new HashMap();
        map98.put(zzbcVarG98.annotationType(), zzbcVarG98);
        zzaU = new C2294b("aggregatedOnDeviceDocumentCroppingLogEvent", c.r(map98));
        zzbc zzbcVarG99 = AbstractC1173g.g(102);
        HashMap map99 = new HashMap();
        map99.put(zzbcVarG99.annotationType(), zzbcVarG99);
        zzaV = new C2294b("onDeviceDocumentEnhancementCreateLogEvent", c.r(map99));
        zzbc zzbcVarG100 = AbstractC1173g.g(103);
        HashMap map100 = new HashMap();
        map100.put(zzbcVarG100.annotationType(), zzbcVarG100);
        zzaW = new C2294b("onDeviceDocumentEnhancementLoadLogEvent", c.r(map100));
        zzbc zzbcVarG101 = AbstractC1173g.g(104);
        HashMap map101 = new HashMap();
        map101.put(zzbcVarG101.annotationType(), zzbcVarG101);
        zzaX = new C2294b("onDeviceDocumentEnhancementLogEvent", c.r(map101));
        zzbc zzbcVarG102 = AbstractC1173g.g(105);
        HashMap map102 = new HashMap();
        map102.put(zzbcVarG102.annotationType(), zzbcVarG102);
        zzaY = new C2294b("aggregatedOnDeviceDocumentEnhancementLogEvent", c.r(map102));
        zzbc zzbcVarG103 = AbstractC1173g.g(106);
        HashMap map103 = new HashMap();
        map103.put(zzbcVarG103.annotationType(), zzbcVarG103);
        zzaZ = new C2294b("scannerAutoZoomEvent", c.r(map103));
        zzbc zzbcVarG104 = AbstractC1173g.g(107);
        HashMap map104 = new HashMap();
        map104.put(zzbcVarG104.annotationType(), zzbcVarG104);
        zzba = new C2294b("lowLightAutoExposureComputationEvent", c.r(map104));
        zzbc zzbcVarG105 = AbstractC1173g.g(108);
        HashMap map105 = new HashMap();
        map105.put(zzbcVarG105.annotationType(), zzbcVarG105);
        zzbb = new C2294b("lowLightFrameProcessEvent", c.r(map105));
        zzbc zzbcVarG106 = AbstractC1173g.g(109);
        HashMap map106 = new HashMap();
        map106.put(zzbcVarG106.annotationType(), zzbcVarG106);
        zzbc = new C2294b("lowLightSceneDetectionEvent", c.r(map106));
        zzbc zzbcVarG107 = AbstractC1173g.g(110);
        HashMap map107 = new HashMap();
        map107.put(zzbcVarG107.annotationType(), zzbcVarG107);
        zzbd = new C2294b("onDeviceStainRemovalLogEvent", c.r(map107));
        zzbc zzbcVarG108 = AbstractC1173g.g(111);
        HashMap map108 = new HashMap();
        map108.put(zzbcVarG108.annotationType(), zzbcVarG108);
        zzbe = new C2294b("aggregatedOnDeviceStainRemovalLogEvent", c.r(map108));
        zzbf = AbstractC1173g.r(112, C2294b.a("stainRemovalOptionalModuleLogEvent"));
        zzbg = AbstractC1173g.r(113, C2294b.a("onDeviceShadowRemovalLogEvent"));
        zzbh = AbstractC1173g.r(114, C2294b.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        zzbi = AbstractC1173g.r(115, C2294b.a("shadowRemovalOptionalModuleLogEvent"));
        zzbj = AbstractC1173g.r(116, C2294b.a("onDeviceDigitalInkSegmentationLogEvent"));
        zzbk = AbstractC1173g.r(117, C2294b.a("onDeviceDocumentScannerStartLogEvent"));
        zzbl = AbstractC1173g.r(118, C2294b.a("onDeviceDocumentScannerFinishLogEvent"));
        zzbm = AbstractC1173g.r(119, C2294b.a("onDeviceDocumentScannerUiStartLogEvent"));
        zzbn = AbstractC1173g.r(120, C2294b.a("onDeviceDocumentScannerUiFinishLogEvent"));
        zzbo = AbstractC1173g.r(121, C2294b.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        zzbp = AbstractC1173g.r(122, C2294b.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        zzbq = AbstractC1173g.r(123, C2294b.a("onDeviceDocumentScannerUiCreateLogEvent"));
        zzbr = AbstractC1173g.r(124, C2294b.a("onDeviceSubjectSegmentationCreateLogEvent"));
        zzbs = AbstractC1173g.r(125, C2294b.a("onDeviceSubjectSegmentationLoadLogEvent"));
        zzbt = AbstractC1173g.r(126, C2294b.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        zzbu = AbstractC1173g.r(127, C2294b.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        zzbv = AbstractC1173g.r(128, C2294b.a("subjectSegmentationOptionalModuleLogEvent"));
        zzbw = AbstractC1173g.r(TsExtractor.TS_STREAM_TYPE_AC3, C2294b.a("documentScannerUiModuleScreenViewEvent"));
        zzbx = AbstractC1173g.r(130, C2294b.a("documentScannerUiModuleScreenClickEvent"));
        zzby = AbstractC1173g.r(131, C2294b.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private zzgp() {
    }

    @Override // u2.InterfaceC2293a
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzmy zzmyVar = (zzmy) obj;
        InterfaceC2296d interfaceC2296d = (InterfaceC2296d) obj2;
        interfaceC2296d.add(zzb, zzmyVar.zzf());
        interfaceC2296d.add(zzc, zzmyVar.zzd());
        interfaceC2296d.add(zzd, (Object) null);
        interfaceC2296d.add(zze, (Object) null);
        interfaceC2296d.add(zzf, zzmyVar.zze());
        interfaceC2296d.add(zzg, (Object) null);
        interfaceC2296d.add(zzh, (Object) null);
        interfaceC2296d.add(zzi, (Object) null);
        interfaceC2296d.add(zzj, (Object) null);
        interfaceC2296d.add(zzk, (Object) null);
        interfaceC2296d.add(zzl, (Object) null);
        interfaceC2296d.add(zzm, (Object) null);
        interfaceC2296d.add(zzn, (Object) null);
        interfaceC2296d.add(zzo, (Object) null);
        interfaceC2296d.add(zzp, (Object) null);
        interfaceC2296d.add(zzq, (Object) null);
        interfaceC2296d.add(zzr, (Object) null);
        interfaceC2296d.add(zzs, (Object) null);
        interfaceC2296d.add(zzt, (Object) null);
        interfaceC2296d.add(zzu, (Object) null);
        interfaceC2296d.add(zzv, (Object) null);
        interfaceC2296d.add(zzw, (Object) null);
        interfaceC2296d.add(zzx, (Object) null);
        interfaceC2296d.add(zzy, (Object) null);
        interfaceC2296d.add(zzz, (Object) null);
        interfaceC2296d.add(zzA, (Object) null);
        interfaceC2296d.add(zzB, (Object) null);
        interfaceC2296d.add(zzC, (Object) null);
        interfaceC2296d.add(zzD, (Object) null);
        interfaceC2296d.add(zzE, (Object) null);
        interfaceC2296d.add(zzF, (Object) null);
        interfaceC2296d.add(zzG, (Object) null);
        interfaceC2296d.add(zzH, (Object) null);
        interfaceC2296d.add(zzI, (Object) null);
        interfaceC2296d.add(zzJ, (Object) null);
        interfaceC2296d.add(zzK, (Object) null);
        interfaceC2296d.add(zzL, (Object) null);
        interfaceC2296d.add(zzM, (Object) null);
        interfaceC2296d.add(zzN, zzmyVar.zzb());
        interfaceC2296d.add(zzO, zzmyVar.zza());
        interfaceC2296d.add(zzP, (Object) null);
        interfaceC2296d.add(zzQ, (Object) null);
        interfaceC2296d.add(zzR, (Object) null);
        interfaceC2296d.add(zzS, (Object) null);
        interfaceC2296d.add(zzT, (Object) null);
        interfaceC2296d.add(zzU, (Object) null);
        interfaceC2296d.add(zzV, (Object) null);
        interfaceC2296d.add(zzW, (Object) null);
        interfaceC2296d.add(zzX, (Object) null);
        interfaceC2296d.add(zzY, (Object) null);
        interfaceC2296d.add(zzZ, (Object) null);
        interfaceC2296d.add(zzaa, (Object) null);
        interfaceC2296d.add(zzab, zzmyVar.zzc());
        interfaceC2296d.add(zzac, (Object) null);
        interfaceC2296d.add(zzad, (Object) null);
        interfaceC2296d.add(zzae, (Object) null);
        interfaceC2296d.add(zzaf, (Object) null);
        interfaceC2296d.add(zzag, (Object) null);
        interfaceC2296d.add(zzah, (Object) null);
        interfaceC2296d.add(zzai, (Object) null);
        interfaceC2296d.add(zzaj, (Object) null);
        interfaceC2296d.add(zzak, (Object) null);
        interfaceC2296d.add(zzal, (Object) null);
        interfaceC2296d.add(zzam, (Object) null);
        interfaceC2296d.add(zzan, (Object) null);
        interfaceC2296d.add(zzao, (Object) null);
        interfaceC2296d.add(zzap, (Object) null);
        interfaceC2296d.add(zzaq, (Object) null);
        interfaceC2296d.add(zzar, (Object) null);
        interfaceC2296d.add(zzas, (Object) null);
        interfaceC2296d.add(zzat, (Object) null);
        interfaceC2296d.add(zzau, (Object) null);
        interfaceC2296d.add(zzav, (Object) null);
        interfaceC2296d.add(zzaw, (Object) null);
        interfaceC2296d.add(zzax, (Object) null);
        interfaceC2296d.add(zzay, (Object) null);
        interfaceC2296d.add(zzaz, (Object) null);
        interfaceC2296d.add(zzaA, (Object) null);
        interfaceC2296d.add(zzaB, (Object) null);
        interfaceC2296d.add(zzaC, (Object) null);
        interfaceC2296d.add(zzaD, (Object) null);
        interfaceC2296d.add(zzaE, (Object) null);
        interfaceC2296d.add(zzaF, (Object) null);
        interfaceC2296d.add(zzaG, (Object) null);
        interfaceC2296d.add(zzaH, (Object) null);
        interfaceC2296d.add(zzaI, (Object) null);
        interfaceC2296d.add(zzaJ, (Object) null);
        interfaceC2296d.add(zzaK, (Object) null);
        interfaceC2296d.add(zzaL, (Object) null);
        interfaceC2296d.add(zzaM, (Object) null);
        interfaceC2296d.add(zzaN, (Object) null);
        interfaceC2296d.add(zzaO, (Object) null);
        interfaceC2296d.add(zzaP, (Object) null);
        interfaceC2296d.add(zzaQ, (Object) null);
        interfaceC2296d.add(zzaR, (Object) null);
        interfaceC2296d.add(zzaS, (Object) null);
        interfaceC2296d.add(zzaT, (Object) null);
        interfaceC2296d.add(zzaU, (Object) null);
        interfaceC2296d.add(zzaV, (Object) null);
        interfaceC2296d.add(zzaW, (Object) null);
        interfaceC2296d.add(zzaX, (Object) null);
        interfaceC2296d.add(zzaY, (Object) null);
        interfaceC2296d.add(zzaZ, (Object) null);
        interfaceC2296d.add(zzba, (Object) null);
        interfaceC2296d.add(zzbb, (Object) null);
        interfaceC2296d.add(zzbc, (Object) null);
        interfaceC2296d.add(zzbd, (Object) null);
        interfaceC2296d.add(zzbe, (Object) null);
        interfaceC2296d.add(zzbf, (Object) null);
        interfaceC2296d.add(zzbg, (Object) null);
        interfaceC2296d.add(zzbh, (Object) null);
        interfaceC2296d.add(zzbi, (Object) null);
        interfaceC2296d.add(zzbj, (Object) null);
        interfaceC2296d.add(zzbk, (Object) null);
        interfaceC2296d.add(zzbl, (Object) null);
        interfaceC2296d.add(zzbm, (Object) null);
        interfaceC2296d.add(zzbn, (Object) null);
        interfaceC2296d.add(zzbo, (Object) null);
        interfaceC2296d.add(zzbp, (Object) null);
        interfaceC2296d.add(zzbq, (Object) null);
        interfaceC2296d.add(zzbr, (Object) null);
        interfaceC2296d.add(zzbs, (Object) null);
        interfaceC2296d.add(zzbt, (Object) null);
        interfaceC2296d.add(zzbu, (Object) null);
        interfaceC2296d.add(zzbv, (Object) null);
        interfaceC2296d.add(zzbw, (Object) null);
        interfaceC2296d.add(zzbx, (Object) null);
        interfaceC2296d.add(zzby, (Object) null);
    }
}
