package com.google.android.gms.internal.mlkit_vision_barcode;

import androidx.media3.datasource.cache.c;
import androidx.media3.extractor.ts.TsExtractor;
import com.google.android.gms.internal.ads.AbstractC1173g;
import java.io.IOException;
import java.util.HashMap;
import u2.C2294b;
import u2.InterfaceC2295c;
import u2.InterfaceC2296d;

/* JADX INFO: loaded from: classes3.dex */
final class zzkv implements InterfaceC2295c {
    private static final C2294b zzA;
    private static final C2294b zzB;
    private static final C2294b zzC;
    private static final C2294b zzD;
    private static final C2294b zzE;
    private static final C2294b zzF;
    private static final C2294b zzG;
    private static final C2294b zzH;
    private static final C2294b zzI;
    private static final C2294b zzJ;
    private static final C2294b zzK;
    private static final C2294b zzL;
    private static final C2294b zzM;
    private static final C2294b zzN;
    private static final C2294b zzO;
    private static final C2294b zzP;
    private static final C2294b zzQ;
    private static final C2294b zzR;
    private static final C2294b zzS;
    private static final C2294b zzT;
    private static final C2294b zzU;
    private static final C2294b zzV;
    private static final C2294b zzW;
    private static final C2294b zzX;
    private static final C2294b zzY;
    private static final C2294b zzZ;
    static final zzkv zza = new zzkv();
    private static final C2294b zzaA;
    private static final C2294b zzaB;
    private static final C2294b zzaC;
    private static final C2294b zzaD;
    private static final C2294b zzaE;
    private static final C2294b zzaF;
    private static final C2294b zzaG;
    private static final C2294b zzaH;
    private static final C2294b zzaI;
    private static final C2294b zzaJ;
    private static final C2294b zzaK;
    private static final C2294b zzaL;
    private static final C2294b zzaM;
    private static final C2294b zzaN;
    private static final C2294b zzaO;
    private static final C2294b zzaP;
    private static final C2294b zzaQ;
    private static final C2294b zzaR;
    private static final C2294b zzaS;
    private static final C2294b zzaT;
    private static final C2294b zzaU;
    private static final C2294b zzaV;
    private static final C2294b zzaW;
    private static final C2294b zzaX;
    private static final C2294b zzaY;
    private static final C2294b zzaZ;
    private static final C2294b zzaa;
    private static final C2294b zzab;
    private static final C2294b zzac;
    private static final C2294b zzad;
    private static final C2294b zzae;
    private static final C2294b zzaf;
    private static final C2294b zzag;
    private static final C2294b zzah;
    private static final C2294b zzai;
    private static final C2294b zzaj;
    private static final C2294b zzak;
    private static final C2294b zzal;
    private static final C2294b zzam;
    private static final C2294b zzan;
    private static final C2294b zzao;
    private static final C2294b zzap;
    private static final C2294b zzaq;
    private static final C2294b zzar;
    private static final C2294b zzas;
    private static final C2294b zzat;
    private static final C2294b zzau;
    private static final C2294b zzav;
    private static final C2294b zzaw;
    private static final C2294b zzax;
    private static final C2294b zzay;
    private static final C2294b zzaz;
    private static final C2294b zzb;
    private static final C2294b zzba;
    private static final C2294b zzbb;
    private static final C2294b zzbc;
    private static final C2294b zzbd;
    private static final C2294b zzbe;
    private static final C2294b zzbf;
    private static final C2294b zzbg;
    private static final C2294b zzbh;
    private static final C2294b zzbi;
    private static final C2294b zzbj;
    private static final C2294b zzbk;
    private static final C2294b zzbl;
    private static final C2294b zzbm;
    private static final C2294b zzbn;
    private static final C2294b zzbo;
    private static final C2294b zzbp;
    private static final C2294b zzbq;
    private static final C2294b zzbr;
    private static final C2294b zzbs;
    private static final C2294b zzbt;
    private static final C2294b zzbu;
    private static final C2294b zzbv;
    private static final C2294b zzbw;
    private static final C2294b zzbx;
    private static final C2294b zzby;
    private static final C2294b zzc;
    private static final C2294b zzd;
    private static final C2294b zze;
    private static final C2294b zzf;
    private static final C2294b zzg;
    private static final C2294b zzh;
    private static final C2294b zzi;
    private static final C2294b zzj;
    private static final C2294b zzk;
    private static final C2294b zzl;
    private static final C2294b zzm;
    private static final C2294b zzn;
    private static final C2294b zzo;
    private static final C2294b zzp;
    private static final C2294b zzq;
    private static final C2294b zzr;
    private static final C2294b zzs;
    private static final C2294b zzt;
    private static final C2294b zzu;
    private static final C2294b zzv;
    private static final C2294b zzw;
    private static final C2294b zzx;
    private static final C2294b zzy;
    private static final C2294b zzz;

    static {
        zzfe zzfeVarI = AbstractC1173g.i(1);
        HashMap map = new HashMap();
        map.put(zzfeVarI.annotationType(), zzfeVarI);
        zzb = new C2294b("systemInfo", c.r(map));
        zzfe zzfeVarI2 = AbstractC1173g.i(2);
        HashMap map2 = new HashMap();
        map2.put(zzfeVarI2.annotationType(), zzfeVarI2);
        zzc = new C2294b("eventName", c.r(map2));
        zzfe zzfeVarI3 = AbstractC1173g.i(37);
        HashMap map3 = new HashMap();
        map3.put(zzfeVarI3.annotationType(), zzfeVarI3);
        zzd = new C2294b("isThickClient", c.r(map3));
        zzfe zzfeVarI4 = AbstractC1173g.i(61);
        HashMap map4 = new HashMap();
        map4.put(zzfeVarI4.annotationType(), zzfeVarI4);
        zze = new C2294b("clientType", c.r(map4));
        zzfe zzfeVarI5 = AbstractC1173g.i(3);
        HashMap map5 = new HashMap();
        map5.put(zzfeVarI5.annotationType(), zzfeVarI5);
        zzf = new C2294b("modelDownloadLogEvent", c.r(map5));
        zzfe zzfeVarI6 = AbstractC1173g.i(20);
        HashMap map6 = new HashMap();
        map6.put(zzfeVarI6.annotationType(), zzfeVarI6);
        zzg = new C2294b("customModelLoadLogEvent", c.r(map6));
        zzfe zzfeVarI7 = AbstractC1173g.i(4);
        HashMap map7 = new HashMap();
        map7.put(zzfeVarI7.annotationType(), zzfeVarI7);
        zzh = new C2294b("customModelInferenceLogEvent", c.r(map7));
        zzfe zzfeVarI8 = AbstractC1173g.i(29);
        HashMap map8 = new HashMap();
        map8.put(zzfeVarI8.annotationType(), zzfeVarI8);
        zzi = new C2294b("customModelCreateLogEvent", c.r(map8));
        zzfe zzfeVarI9 = AbstractC1173g.i(5);
        HashMap map9 = new HashMap();
        map9.put(zzfeVarI9.annotationType(), zzfeVarI9);
        zzj = new C2294b("onDeviceFaceDetectionLogEvent", c.r(map9));
        zzfe zzfeVarI10 = AbstractC1173g.i(59);
        HashMap map10 = new HashMap();
        map10.put(zzfeVarI10.annotationType(), zzfeVarI10);
        zzk = new C2294b("onDeviceFaceLoadLogEvent", c.r(map10));
        zzfe zzfeVarI11 = AbstractC1173g.i(6);
        HashMap map11 = new HashMap();
        map11.put(zzfeVarI11.annotationType(), zzfeVarI11);
        zzl = new C2294b("onDeviceTextDetectionLogEvent", c.r(map11));
        zzfe zzfeVarI12 = AbstractC1173g.i(79);
        HashMap map12 = new HashMap();
        map12.put(zzfeVarI12.annotationType(), zzfeVarI12);
        zzm = new C2294b("onDeviceTextDetectionLoadLogEvent", c.r(map12));
        zzfe zzfeVarI13 = AbstractC1173g.i(7);
        HashMap map13 = new HashMap();
        map13.put(zzfeVarI13.annotationType(), zzfeVarI13);
        zzn = new C2294b("onDeviceBarcodeDetectionLogEvent", c.r(map13));
        zzfe zzfeVarI14 = AbstractC1173g.i(58);
        HashMap map14 = new HashMap();
        map14.put(zzfeVarI14.annotationType(), zzfeVarI14);
        zzo = new C2294b("onDeviceBarcodeLoadLogEvent", c.r(map14));
        zzfe zzfeVarI15 = AbstractC1173g.i(48);
        HashMap map15 = new HashMap();
        map15.put(zzfeVarI15.annotationType(), zzfeVarI15);
        zzp = new C2294b("onDeviceImageLabelCreateLogEvent", c.r(map15));
        zzfe zzfeVarI16 = AbstractC1173g.i(49);
        HashMap map16 = new HashMap();
        map16.put(zzfeVarI16.annotationType(), zzfeVarI16);
        zzq = new C2294b("onDeviceImageLabelLoadLogEvent", c.r(map16));
        zzfe zzfeVarI17 = AbstractC1173g.i(18);
        HashMap map17 = new HashMap();
        map17.put(zzfeVarI17.annotationType(), zzfeVarI17);
        zzr = new C2294b("onDeviceImageLabelDetectionLogEvent", c.r(map17));
        zzfe zzfeVarI18 = AbstractC1173g.i(26);
        HashMap map18 = new HashMap();
        map18.put(zzfeVarI18.annotationType(), zzfeVarI18);
        zzs = new C2294b("onDeviceObjectCreateLogEvent", c.r(map18));
        zzfe zzfeVarI19 = AbstractC1173g.i(27);
        HashMap map19 = new HashMap();
        map19.put(zzfeVarI19.annotationType(), zzfeVarI19);
        zzt = new C2294b("onDeviceObjectLoadLogEvent", c.r(map19));
        zzfe zzfeVarI20 = AbstractC1173g.i(28);
        HashMap map20 = new HashMap();
        map20.put(zzfeVarI20.annotationType(), zzfeVarI20);
        zzu = new C2294b("onDeviceObjectInferenceLogEvent", c.r(map20));
        zzfe zzfeVarI21 = AbstractC1173g.i(44);
        HashMap map21 = new HashMap();
        map21.put(zzfeVarI21.annotationType(), zzfeVarI21);
        zzv = new C2294b("onDevicePoseDetectionLogEvent", c.r(map21));
        zzfe zzfeVarI22 = AbstractC1173g.i(45);
        HashMap map22 = new HashMap();
        map22.put(zzfeVarI22.annotationType(), zzfeVarI22);
        zzw = new C2294b("onDeviceSegmentationLogEvent", c.r(map22));
        zzfe zzfeVarI23 = AbstractC1173g.i(19);
        HashMap map23 = new HashMap();
        map23.put(zzfeVarI23.annotationType(), zzfeVarI23);
        zzx = new C2294b("onDeviceSmartReplyLogEvent", c.r(map23));
        zzfe zzfeVarI24 = AbstractC1173g.i(21);
        HashMap map24 = new HashMap();
        map24.put(zzfeVarI24.annotationType(), zzfeVarI24);
        zzy = new C2294b("onDeviceLanguageIdentificationLogEvent", c.r(map24));
        zzfe zzfeVarI25 = AbstractC1173g.i(22);
        HashMap map25 = new HashMap();
        map25.put(zzfeVarI25.annotationType(), zzfeVarI25);
        zzz = new C2294b("onDeviceTranslationLogEvent", c.r(map25));
        zzfe zzfeVarI26 = AbstractC1173g.i(8);
        HashMap map26 = new HashMap();
        map26.put(zzfeVarI26.annotationType(), zzfeVarI26);
        zzA = new C2294b("cloudFaceDetectionLogEvent", c.r(map26));
        zzfe zzfeVarI27 = AbstractC1173g.i(9);
        HashMap map27 = new HashMap();
        map27.put(zzfeVarI27.annotationType(), zzfeVarI27);
        zzB = new C2294b("cloudCropHintDetectionLogEvent", c.r(map27));
        zzfe zzfeVarI28 = AbstractC1173g.i(10);
        HashMap map28 = new HashMap();
        map28.put(zzfeVarI28.annotationType(), zzfeVarI28);
        zzC = new C2294b("cloudDocumentTextDetectionLogEvent", c.r(map28));
        zzfe zzfeVarI29 = AbstractC1173g.i(11);
        HashMap map29 = new HashMap();
        map29.put(zzfeVarI29.annotationType(), zzfeVarI29);
        zzD = new C2294b("cloudImagePropertiesDetectionLogEvent", c.r(map29));
        zzfe zzfeVarI30 = AbstractC1173g.i(12);
        HashMap map30 = new HashMap();
        map30.put(zzfeVarI30.annotationType(), zzfeVarI30);
        zzE = new C2294b("cloudImageLabelDetectionLogEvent", c.r(map30));
        zzfe zzfeVarI31 = AbstractC1173g.i(13);
        HashMap map31 = new HashMap();
        map31.put(zzfeVarI31.annotationType(), zzfeVarI31);
        zzF = new C2294b("cloudLandmarkDetectionLogEvent", c.r(map31));
        zzfe zzfeVarI32 = AbstractC1173g.i(14);
        HashMap map32 = new HashMap();
        map32.put(zzfeVarI32.annotationType(), zzfeVarI32);
        zzG = new C2294b("cloudLogoDetectionLogEvent", c.r(map32));
        zzfe zzfeVarI33 = AbstractC1173g.i(15);
        HashMap map33 = new HashMap();
        map33.put(zzfeVarI33.annotationType(), zzfeVarI33);
        zzH = new C2294b("cloudSafeSearchDetectionLogEvent", c.r(map33));
        zzfe zzfeVarI34 = AbstractC1173g.i(16);
        HashMap map34 = new HashMap();
        map34.put(zzfeVarI34.annotationType(), zzfeVarI34);
        zzI = new C2294b("cloudTextDetectionLogEvent", c.r(map34));
        zzfe zzfeVarI35 = AbstractC1173g.i(17);
        HashMap map35 = new HashMap();
        map35.put(zzfeVarI35.annotationType(), zzfeVarI35);
        zzJ = new C2294b("cloudWebSearchDetectionLogEvent", c.r(map35));
        zzfe zzfeVarI36 = AbstractC1173g.i(23);
        HashMap map36 = new HashMap();
        map36.put(zzfeVarI36.annotationType(), zzfeVarI36);
        zzK = new C2294b("automlImageLabelingCreateLogEvent", c.r(map36));
        zzfe zzfeVarI37 = AbstractC1173g.i(24);
        HashMap map37 = new HashMap();
        map37.put(zzfeVarI37.annotationType(), zzfeVarI37);
        zzL = new C2294b("automlImageLabelingLoadLogEvent", c.r(map37));
        zzfe zzfeVarI38 = AbstractC1173g.i(25);
        HashMap map38 = new HashMap();
        map38.put(zzfeVarI38.annotationType(), zzfeVarI38);
        zzM = new C2294b("automlImageLabelingInferenceLogEvent", c.r(map38));
        zzfe zzfeVarI39 = AbstractC1173g.i(39);
        HashMap map39 = new HashMap();
        map39.put(zzfeVarI39.annotationType(), zzfeVarI39);
        zzN = new C2294b("isModelDownloadedLogEvent", c.r(map39));
        zzfe zzfeVarI40 = AbstractC1173g.i(40);
        HashMap map40 = new HashMap();
        map40.put(zzfeVarI40.annotationType(), zzfeVarI40);
        zzO = new C2294b("deleteModelLogEvent", c.r(map40));
        zzfe zzfeVarI41 = AbstractC1173g.i(30);
        HashMap map41 = new HashMap();
        map41.put(zzfeVarI41.annotationType(), zzfeVarI41);
        zzP = new C2294b("aggregatedAutomlImageLabelingInferenceLogEvent", c.r(map41));
        zzfe zzfeVarI42 = AbstractC1173g.i(31);
        HashMap map42 = new HashMap();
        map42.put(zzfeVarI42.annotationType(), zzfeVarI42);
        zzQ = new C2294b("aggregatedCustomModelInferenceLogEvent", c.r(map42));
        zzfe zzfeVarI43 = AbstractC1173g.i(32);
        HashMap map43 = new HashMap();
        map43.put(zzfeVarI43.annotationType(), zzfeVarI43);
        zzR = new C2294b("aggregatedOnDeviceFaceDetectionLogEvent", c.r(map43));
        zzfe zzfeVarI44 = AbstractC1173g.i(33);
        HashMap map44 = new HashMap();
        map44.put(zzfeVarI44.annotationType(), zzfeVarI44);
        zzS = new C2294b("aggregatedOnDeviceBarcodeDetectionLogEvent", c.r(map44));
        zzfe zzfeVarI45 = AbstractC1173g.i(34);
        HashMap map45 = new HashMap();
        map45.put(zzfeVarI45.annotationType(), zzfeVarI45);
        zzT = new C2294b("aggregatedOnDeviceImageLabelDetectionLogEvent", c.r(map45));
        zzfe zzfeVarI46 = AbstractC1173g.i(35);
        HashMap map46 = new HashMap();
        map46.put(zzfeVarI46.annotationType(), zzfeVarI46);
        zzU = new C2294b("aggregatedOnDeviceObjectInferenceLogEvent", c.r(map46));
        zzfe zzfeVarI47 = AbstractC1173g.i(36);
        HashMap map47 = new HashMap();
        map47.put(zzfeVarI47.annotationType(), zzfeVarI47);
        zzV = new C2294b("aggregatedOnDeviceTextDetectionLogEvent", c.r(map47));
        zzfe zzfeVarI48 = AbstractC1173g.i(46);
        HashMap map48 = new HashMap();
        map48.put(zzfeVarI48.annotationType(), zzfeVarI48);
        zzW = new C2294b("aggregatedOnDevicePoseDetectionLogEvent", c.r(map48));
        zzfe zzfeVarI49 = AbstractC1173g.i(47);
        HashMap map49 = new HashMap();
        map49.put(zzfeVarI49.annotationType(), zzfeVarI49);
        zzX = new C2294b("aggregatedOnDeviceSegmentationLogEvent", c.r(map49));
        zzfe zzfeVarI50 = AbstractC1173g.i(69);
        HashMap map50 = new HashMap();
        map50.put(zzfeVarI50.annotationType(), zzfeVarI50);
        zzY = new C2294b("pipelineAccelerationInferenceEvents", c.r(map50));
        zzfe zzfeVarI51 = AbstractC1173g.i(42);
        HashMap map51 = new HashMap();
        map51.put(zzfeVarI51.annotationType(), zzfeVarI51);
        zzZ = new C2294b("remoteConfigLogEvent", c.r(map51));
        zzfe zzfeVarI52 = AbstractC1173g.i(50);
        HashMap map52 = new HashMap();
        map52.put(zzfeVarI52.annotationType(), zzfeVarI52);
        zzaa = new C2294b("inputImageConstructionLogEvent", c.r(map52));
        zzfe zzfeVarI53 = AbstractC1173g.i(51);
        HashMap map53 = new HashMap();
        map53.put(zzfeVarI53.annotationType(), zzfeVarI53);
        zzab = new C2294b("leakedHandleEvent", c.r(map53));
        zzfe zzfeVarI54 = AbstractC1173g.i(52);
        HashMap map54 = new HashMap();
        map54.put(zzfeVarI54.annotationType(), zzfeVarI54);
        zzac = new C2294b("cameraSourceLogEvent", c.r(map54));
        zzfe zzfeVarI55 = AbstractC1173g.i(53);
        HashMap map55 = new HashMap();
        map55.put(zzfeVarI55.annotationType(), zzfeVarI55);
        zzad = new C2294b("imageLabelOptionalModuleLogEvent", c.r(map55));
        zzfe zzfeVarI56 = AbstractC1173g.i(54);
        HashMap map56 = new HashMap();
        map56.put(zzfeVarI56.annotationType(), zzfeVarI56);
        zzae = new C2294b("languageIdentificationOptionalModuleLogEvent", c.r(map56));
        zzfe zzfeVarI57 = AbstractC1173g.i(60);
        HashMap map57 = new HashMap();
        map57.put(zzfeVarI57.annotationType(), zzfeVarI57);
        zzaf = new C2294b("faceDetectionOptionalModuleLogEvent", c.r(map57));
        zzfe zzfeVarI58 = AbstractC1173g.i(85);
        HashMap map58 = new HashMap();
        map58.put(zzfeVarI58.annotationType(), zzfeVarI58);
        zzag = new C2294b("documentDetectionOptionalModuleLogEvent", c.r(map58));
        zzfe zzfeVarI59 = AbstractC1173g.i(86);
        HashMap map59 = new HashMap();
        map59.put(zzfeVarI59.annotationType(), zzfeVarI59);
        zzah = new C2294b("documentCroppingOptionalModuleLogEvent", c.r(map59));
        zzfe zzfeVarI60 = AbstractC1173g.i(87);
        HashMap map60 = new HashMap();
        map60.put(zzfeVarI60.annotationType(), zzfeVarI60);
        zzai = new C2294b("documentEnhancementOptionalModuleLogEvent", c.r(map60));
        zzfe zzfeVarI61 = AbstractC1173g.i(55);
        HashMap map61 = new HashMap();
        map61.put(zzfeVarI61.annotationType(), zzfeVarI61);
        zzaj = new C2294b("nlClassifierOptionalModuleLogEvent", c.r(map61));
        zzfe zzfeVarI62 = AbstractC1173g.i(56);
        HashMap map62 = new HashMap();
        map62.put(zzfeVarI62.annotationType(), zzfeVarI62);
        zzak = new C2294b("nlClassifierClientLibraryLogEvent", c.r(map62));
        zzfe zzfeVarI63 = AbstractC1173g.i(57);
        HashMap map63 = new HashMap();
        map63.put(zzfeVarI63.annotationType(), zzfeVarI63);
        zzal = new C2294b("accelerationAllowlistLogEvent", c.r(map63));
        zzfe zzfeVarI64 = AbstractC1173g.i(62);
        HashMap map64 = new HashMap();
        map64.put(zzfeVarI64.annotationType(), zzfeVarI64);
        zzam = new C2294b("toxicityDetectionCreateEvent", c.r(map64));
        zzfe zzfeVarI65 = AbstractC1173g.i(63);
        HashMap map65 = new HashMap();
        map65.put(zzfeVarI65.annotationType(), zzfeVarI65);
        zzan = new C2294b("toxicityDetectionLoadEvent", c.r(map65));
        zzfe zzfeVarI66 = AbstractC1173g.i(64);
        HashMap map66 = new HashMap();
        map66.put(zzfeVarI66.annotationType(), zzfeVarI66);
        zzao = new C2294b("toxicityDetectionInferenceEvent", c.r(map66));
        zzfe zzfeVarI67 = AbstractC1173g.i(65);
        HashMap map67 = new HashMap();
        map67.put(zzfeVarI67.annotationType(), zzfeVarI67);
        zzap = new C2294b("barcodeDetectionOptionalModuleLogEvent", c.r(map67));
        zzfe zzfeVarI68 = AbstractC1173g.i(66);
        HashMap map68 = new HashMap();
        map68.put(zzfeVarI68.annotationType(), zzfeVarI68);
        zzaq = new C2294b("customImageLabelOptionalModuleLogEvent", c.r(map68));
        zzfe zzfeVarI69 = AbstractC1173g.i(67);
        HashMap map69 = new HashMap();
        map69.put(zzfeVarI69.annotationType(), zzfeVarI69);
        zzar = new C2294b("codeScannerScanApiEvent", c.r(map69));
        zzfe zzfeVarI70 = AbstractC1173g.i(68);
        HashMap map70 = new HashMap();
        map70.put(zzfeVarI70.annotationType(), zzfeVarI70);
        zzas = new C2294b("codeScannerOptionalModuleEvent", c.r(map70));
        zzfe zzfeVarI71 = AbstractC1173g.i(70);
        HashMap map71 = new HashMap();
        map71.put(zzfeVarI71.annotationType(), zzfeVarI71);
        zzat = new C2294b("onDeviceExplicitContentCreateLogEvent", c.r(map71));
        zzfe zzfeVarI72 = AbstractC1173g.i(71);
        HashMap map72 = new HashMap();
        map72.put(zzfeVarI72.annotationType(), zzfeVarI72);
        zzau = new C2294b("onDeviceExplicitContentLoadLogEvent", c.r(map72));
        zzfe zzfeVarI73 = AbstractC1173g.i(72);
        HashMap map73 = new HashMap();
        map73.put(zzfeVarI73.annotationType(), zzfeVarI73);
        zzav = new C2294b("onDeviceExplicitContentInferenceLogEvent", c.r(map73));
        zzfe zzfeVarI74 = AbstractC1173g.i(73);
        HashMap map74 = new HashMap();
        map74.put(zzfeVarI74.annotationType(), zzfeVarI74);
        zzaw = new C2294b("aggregatedOnDeviceExplicitContentLogEvent", c.r(map74));
        zzfe zzfeVarI75 = AbstractC1173g.i(74);
        HashMap map75 = new HashMap();
        map75.put(zzfeVarI75.annotationType(), zzfeVarI75);
        zzax = new C2294b("onDeviceFaceMeshCreateLogEvent", c.r(map75));
        zzfe zzfeVarI76 = AbstractC1173g.i(75);
        HashMap map76 = new HashMap();
        map76.put(zzfeVarI76.annotationType(), zzfeVarI76);
        zzay = new C2294b("onDeviceFaceMeshLoadLogEvent", c.r(map76));
        zzfe zzfeVarI77 = AbstractC1173g.i(76);
        HashMap map77 = new HashMap();
        map77.put(zzfeVarI77.annotationType(), zzfeVarI77);
        zzaz = new C2294b("onDeviceFaceMeshLogEvent", c.r(map77));
        zzfe zzfeVarI78 = AbstractC1173g.i(77);
        HashMap map78 = new HashMap();
        map78.put(zzfeVarI78.annotationType(), zzfeVarI78);
        zzaA = new C2294b("aggregatedOnDeviceFaceMeshLogEvent", c.r(map78));
        zzfe zzfeVarI79 = AbstractC1173g.i(78);
        HashMap map79 = new HashMap();
        map79.put(zzfeVarI79.annotationType(), zzfeVarI79);
        zzaB = new C2294b("smartReplyOptionalModuleLogEvent", c.r(map79));
        zzfe zzfeVarI80 = AbstractC1173g.i(80);
        HashMap map80 = new HashMap();
        map80.put(zzfeVarI80.annotationType(), zzfeVarI80);
        zzaC = new C2294b("textDetectionOptionalModuleLogEvent", c.r(map80));
        zzfe zzfeVarI81 = AbstractC1173g.i(81);
        HashMap map81 = new HashMap();
        map81.put(zzfeVarI81.annotationType(), zzfeVarI81);
        zzaD = new C2294b("onDeviceImageQualityAnalysisCreateLogEvent", c.r(map81));
        zzfe zzfeVarI82 = AbstractC1173g.i(82);
        HashMap map82 = new HashMap();
        map82.put(zzfeVarI82.annotationType(), zzfeVarI82);
        zzaE = new C2294b("onDeviceImageQualityAnalysisLoadLogEvent", c.r(map82));
        zzfe zzfeVarI83 = AbstractC1173g.i(83);
        HashMap map83 = new HashMap();
        map83.put(zzfeVarI83.annotationType(), zzfeVarI83);
        zzaF = new C2294b("onDeviceImageQualityAnalysisLogEvent", c.r(map83));
        zzfe zzfeVarI84 = AbstractC1173g.i(84);
        HashMap map84 = new HashMap();
        map84.put(zzfeVarI84.annotationType(), zzfeVarI84);
        zzaG = new C2294b("aggregatedOnDeviceImageQualityAnalysisLogEvent", c.r(map84));
        zzfe zzfeVarI85 = AbstractC1173g.i(88);
        HashMap map85 = new HashMap();
        map85.put(zzfeVarI85.annotationType(), zzfeVarI85);
        zzaH = new C2294b("imageQualityAnalysisOptionalModuleLogEvent", c.r(map85));
        zzfe zzfeVarI86 = AbstractC1173g.i(89);
        HashMap map86 = new HashMap();
        map86.put(zzfeVarI86.annotationType(), zzfeVarI86);
        zzaI = new C2294b("imageCaptioningOptionalModuleLogEvent", c.r(map86));
        zzfe zzfeVarI87 = AbstractC1173g.i(90);
        HashMap map87 = new HashMap();
        map87.put(zzfeVarI87.annotationType(), zzfeVarI87);
        zzaJ = new C2294b("onDeviceImageCaptioningCreateLogEvent", c.r(map87));
        zzfe zzfeVarI88 = AbstractC1173g.i(91);
        HashMap map88 = new HashMap();
        map88.put(zzfeVarI88.annotationType(), zzfeVarI88);
        zzaK = new C2294b("onDeviceImageCaptioningLoadLogEvent", c.r(map88));
        zzfe zzfeVarI89 = AbstractC1173g.i(92);
        HashMap map89 = new HashMap();
        map89.put(zzfeVarI89.annotationType(), zzfeVarI89);
        zzaL = new C2294b("onDeviceImageCaptioningInferenceLogEvent", c.r(map89));
        zzfe zzfeVarI90 = AbstractC1173g.i(93);
        HashMap map90 = new HashMap();
        map90.put(zzfeVarI90.annotationType(), zzfeVarI90);
        zzaM = new C2294b("aggregatedOnDeviceImageCaptioningInferenceLogEvent", c.r(map90));
        zzfe zzfeVarI91 = AbstractC1173g.i(94);
        HashMap map91 = new HashMap();
        map91.put(zzfeVarI91.annotationType(), zzfeVarI91);
        zzaN = new C2294b("onDeviceDocumentDetectionCreateLogEvent", c.r(map91));
        zzfe zzfeVarI92 = AbstractC1173g.i(95);
        HashMap map92 = new HashMap();
        map92.put(zzfeVarI92.annotationType(), zzfeVarI92);
        zzaO = new C2294b("onDeviceDocumentDetectionLoadLogEvent", c.r(map92));
        zzfe zzfeVarI93 = AbstractC1173g.i(96);
        HashMap map93 = new HashMap();
        map93.put(zzfeVarI93.annotationType(), zzfeVarI93);
        zzaP = new C2294b("onDeviceDocumentDetectionLogEvent", c.r(map93));
        zzfe zzfeVarI94 = AbstractC1173g.i(97);
        HashMap map94 = new HashMap();
        map94.put(zzfeVarI94.annotationType(), zzfeVarI94);
        zzaQ = new C2294b("aggregatedOnDeviceDocumentDetectionLogEvent", c.r(map94));
        zzfe zzfeVarI95 = AbstractC1173g.i(98);
        HashMap map95 = new HashMap();
        map95.put(zzfeVarI95.annotationType(), zzfeVarI95);
        zzaR = new C2294b("onDeviceDocumentCroppingCreateLogEvent", c.r(map95));
        zzfe zzfeVarI96 = AbstractC1173g.i(99);
        HashMap map96 = new HashMap();
        map96.put(zzfeVarI96.annotationType(), zzfeVarI96);
        zzaS = new C2294b("onDeviceDocumentCroppingLoadLogEvent", c.r(map96));
        zzfe zzfeVarI97 = AbstractC1173g.i(100);
        HashMap map97 = new HashMap();
        map97.put(zzfeVarI97.annotationType(), zzfeVarI97);
        zzaT = new C2294b("onDeviceDocumentCroppingLogEvent", c.r(map97));
        zzfe zzfeVarI98 = AbstractC1173g.i(101);
        HashMap map98 = new HashMap();
        map98.put(zzfeVarI98.annotationType(), zzfeVarI98);
        zzaU = new C2294b("aggregatedOnDeviceDocumentCroppingLogEvent", c.r(map98));
        zzfe zzfeVarI99 = AbstractC1173g.i(102);
        HashMap map99 = new HashMap();
        map99.put(zzfeVarI99.annotationType(), zzfeVarI99);
        zzaV = new C2294b("onDeviceDocumentEnhancementCreateLogEvent", c.r(map99));
        zzfe zzfeVarI100 = AbstractC1173g.i(103);
        HashMap map100 = new HashMap();
        map100.put(zzfeVarI100.annotationType(), zzfeVarI100);
        zzaW = new C2294b("onDeviceDocumentEnhancementLoadLogEvent", c.r(map100));
        zzfe zzfeVarI101 = AbstractC1173g.i(104);
        HashMap map101 = new HashMap();
        map101.put(zzfeVarI101.annotationType(), zzfeVarI101);
        zzaX = new C2294b("onDeviceDocumentEnhancementLogEvent", c.r(map101));
        zzfe zzfeVarI102 = AbstractC1173g.i(105);
        HashMap map102 = new HashMap();
        map102.put(zzfeVarI102.annotationType(), zzfeVarI102);
        zzaY = new C2294b("aggregatedOnDeviceDocumentEnhancementLogEvent", c.r(map102));
        zzfe zzfeVarI103 = AbstractC1173g.i(106);
        HashMap map103 = new HashMap();
        map103.put(zzfeVarI103.annotationType(), zzfeVarI103);
        zzaZ = new C2294b("scannerAutoZoomEvent", c.r(map103));
        zzfe zzfeVarI104 = AbstractC1173g.i(107);
        HashMap map104 = new HashMap();
        map104.put(zzfeVarI104.annotationType(), zzfeVarI104);
        zzba = new C2294b("lowLightAutoExposureComputationEvent", c.r(map104));
        zzfe zzfeVarI105 = AbstractC1173g.i(108);
        HashMap map105 = new HashMap();
        map105.put(zzfeVarI105.annotationType(), zzfeVarI105);
        zzbb = new C2294b("lowLightFrameProcessEvent", c.r(map105));
        zzfe zzfeVarI106 = AbstractC1173g.i(109);
        HashMap map106 = new HashMap();
        map106.put(zzfeVarI106.annotationType(), zzfeVarI106);
        zzbc = new C2294b("lowLightSceneDetectionEvent", c.r(map106));
        zzfe zzfeVarI107 = AbstractC1173g.i(110);
        HashMap map107 = new HashMap();
        map107.put(zzfeVarI107.annotationType(), zzfeVarI107);
        zzbd = new C2294b("onDeviceStainRemovalLogEvent", c.r(map107));
        zzfe zzfeVarI108 = AbstractC1173g.i(111);
        HashMap map108 = new HashMap();
        map108.put(zzfeVarI108.annotationType(), zzfeVarI108);
        zzbe = new C2294b("aggregatedOnDeviceStainRemovalLogEvent", c.r(map108));
        zzbf = AbstractC1173g.A(112, C2294b.a("stainRemovalOptionalModuleLogEvent"));
        zzbg = AbstractC1173g.A(113, C2294b.a("onDeviceShadowRemovalLogEvent"));
        zzbh = AbstractC1173g.A(114, C2294b.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        zzbi = AbstractC1173g.A(115, C2294b.a("shadowRemovalOptionalModuleLogEvent"));
        zzbj = AbstractC1173g.A(116, C2294b.a("onDeviceDigitalInkSegmentationLogEvent"));
        zzbk = AbstractC1173g.A(117, C2294b.a("onDeviceDocumentScannerStartLogEvent"));
        zzbl = AbstractC1173g.A(118, C2294b.a("onDeviceDocumentScannerFinishLogEvent"));
        zzbm = AbstractC1173g.A(119, C2294b.a("onDeviceDocumentScannerUiStartLogEvent"));
        zzbn = AbstractC1173g.A(120, C2294b.a("onDeviceDocumentScannerUiFinishLogEvent"));
        zzbo = AbstractC1173g.A(121, C2294b.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        zzbp = AbstractC1173g.A(122, C2294b.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        zzbq = AbstractC1173g.A(123, C2294b.a("onDeviceDocumentScannerUiCreateLogEvent"));
        zzbr = AbstractC1173g.A(124, C2294b.a("onDeviceSubjectSegmentationCreateLogEvent"));
        zzbs = AbstractC1173g.A(125, C2294b.a("onDeviceSubjectSegmentationLoadLogEvent"));
        zzbt = AbstractC1173g.A(126, C2294b.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        zzbu = AbstractC1173g.A(127, C2294b.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        zzbv = AbstractC1173g.A(128, C2294b.a("subjectSegmentationOptionalModuleLogEvent"));
        zzbw = AbstractC1173g.A(TsExtractor.TS_STREAM_TYPE_AC3, C2294b.a("documentScannerUiModuleScreenViewEvent"));
        zzbx = AbstractC1173g.A(130, C2294b.a("documentScannerUiModuleScreenClickEvent"));
        zzby = AbstractC1173g.A(131, C2294b.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private zzkv() {
    }

    @Override // u2.InterfaceC2293a
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzrf zzrfVar = (zzrf) obj;
        InterfaceC2296d interfaceC2296d = (InterfaceC2296d) obj2;
        interfaceC2296d.add(zzb, zzrfVar.zzg());
        interfaceC2296d.add(zzc, zzrfVar.zzc());
        interfaceC2296d.add(zzd, (Object) null);
        interfaceC2296d.add(zze, zzrfVar.zzb());
        interfaceC2296d.add(zzf, (Object) null);
        interfaceC2296d.add(zzg, (Object) null);
        interfaceC2296d.add(zzh, (Object) null);
        interfaceC2296d.add(zzi, (Object) null);
        interfaceC2296d.add(zzj, (Object) null);
        interfaceC2296d.add(zzk, (Object) null);
        interfaceC2296d.add(zzl, (Object) null);
        interfaceC2296d.add(zzm, (Object) null);
        interfaceC2296d.add(zzn, zzrfVar.zzd());
        interfaceC2296d.add(zzo, zzrfVar.zze());
        interfaceC2296d.add(zzp, (Object) null);
        interfaceC2296d.add(zzq, (Object) null);
        interfaceC2296d.add(zzr, (Object) null);
        interfaceC2296d.add(zzs, (Object) null);
        interfaceC2296d.add(zzt, (Object) null);
        interfaceC2296d.add(zzu, (Object) null);
        interfaceC2296d.add(zzv, (Object) null);
        interfaceC2296d.add(zzw, (Object) null);
        interfaceC2296d.add(zzx, (Object) null);
        interfaceC2296d.add(zzy, (Object) null);
        interfaceC2296d.add(zzz, (Object) null);
        interfaceC2296d.add(zzA, (Object) null);
        interfaceC2296d.add(zzB, (Object) null);
        interfaceC2296d.add(zzC, (Object) null);
        interfaceC2296d.add(zzD, (Object) null);
        interfaceC2296d.add(zzE, (Object) null);
        interfaceC2296d.add(zzF, (Object) null);
        interfaceC2296d.add(zzG, (Object) null);
        interfaceC2296d.add(zzH, (Object) null);
        interfaceC2296d.add(zzI, (Object) null);
        interfaceC2296d.add(zzJ, (Object) null);
        interfaceC2296d.add(zzK, (Object) null);
        interfaceC2296d.add(zzL, (Object) null);
        interfaceC2296d.add(zzM, (Object) null);
        interfaceC2296d.add(zzN, (Object) null);
        interfaceC2296d.add(zzO, (Object) null);
        interfaceC2296d.add(zzP, (Object) null);
        interfaceC2296d.add(zzQ, (Object) null);
        interfaceC2296d.add(zzR, (Object) null);
        interfaceC2296d.add(zzS, zzrfVar.zza());
        interfaceC2296d.add(zzT, (Object) null);
        interfaceC2296d.add(zzU, (Object) null);
        interfaceC2296d.add(zzV, (Object) null);
        interfaceC2296d.add(zzW, (Object) null);
        interfaceC2296d.add(zzX, (Object) null);
        interfaceC2296d.add(zzY, (Object) null);
        interfaceC2296d.add(zzZ, (Object) null);
        interfaceC2296d.add(zzaa, (Object) null);
        interfaceC2296d.add(zzab, (Object) null);
        interfaceC2296d.add(zzac, (Object) null);
        interfaceC2296d.add(zzad, (Object) null);
        interfaceC2296d.add(zzae, (Object) null);
        interfaceC2296d.add(zzaf, (Object) null);
        interfaceC2296d.add(zzag, (Object) null);
        interfaceC2296d.add(zzah, (Object) null);
        interfaceC2296d.add(zzai, (Object) null);
        interfaceC2296d.add(zzaj, (Object) null);
        interfaceC2296d.add(zzak, (Object) null);
        interfaceC2296d.add(zzal, (Object) null);
        interfaceC2296d.add(zzam, (Object) null);
        interfaceC2296d.add(zzan, (Object) null);
        interfaceC2296d.add(zzao, (Object) null);
        interfaceC2296d.add(zzap, (Object) null);
        interfaceC2296d.add(zzaq, (Object) null);
        interfaceC2296d.add(zzar, (Object) null);
        interfaceC2296d.add(zzas, (Object) null);
        interfaceC2296d.add(zzat, (Object) null);
        interfaceC2296d.add(zzau, (Object) null);
        interfaceC2296d.add(zzav, (Object) null);
        interfaceC2296d.add(zzaw, (Object) null);
        interfaceC2296d.add(zzax, (Object) null);
        interfaceC2296d.add(zzay, (Object) null);
        interfaceC2296d.add(zzaz, (Object) null);
        interfaceC2296d.add(zzaA, (Object) null);
        interfaceC2296d.add(zzaB, (Object) null);
        interfaceC2296d.add(zzaC, (Object) null);
        interfaceC2296d.add(zzaD, (Object) null);
        interfaceC2296d.add(zzaE, (Object) null);
        interfaceC2296d.add(zzaF, (Object) null);
        interfaceC2296d.add(zzaG, (Object) null);
        interfaceC2296d.add(zzaH, (Object) null);
        interfaceC2296d.add(zzaI, (Object) null);
        interfaceC2296d.add(zzaJ, (Object) null);
        interfaceC2296d.add(zzaK, (Object) null);
        interfaceC2296d.add(zzaL, (Object) null);
        interfaceC2296d.add(zzaM, (Object) null);
        interfaceC2296d.add(zzaN, (Object) null);
        interfaceC2296d.add(zzaO, (Object) null);
        interfaceC2296d.add(zzaP, (Object) null);
        interfaceC2296d.add(zzaQ, (Object) null);
        interfaceC2296d.add(zzaR, (Object) null);
        interfaceC2296d.add(zzaS, (Object) null);
        interfaceC2296d.add(zzaT, (Object) null);
        interfaceC2296d.add(zzaU, (Object) null);
        interfaceC2296d.add(zzaV, (Object) null);
        interfaceC2296d.add(zzaW, (Object) null);
        interfaceC2296d.add(zzaX, (Object) null);
        interfaceC2296d.add(zzaY, (Object) null);
        interfaceC2296d.add(zzaZ, zzrfVar.zzf());
        interfaceC2296d.add(zzba, (Object) null);
        interfaceC2296d.add(zzbb, (Object) null);
        interfaceC2296d.add(zzbc, (Object) null);
        interfaceC2296d.add(zzbd, (Object) null);
        interfaceC2296d.add(zzbe, (Object) null);
        interfaceC2296d.add(zzbf, (Object) null);
        interfaceC2296d.add(zzbg, (Object) null);
        interfaceC2296d.add(zzbh, (Object) null);
        interfaceC2296d.add(zzbi, (Object) null);
        interfaceC2296d.add(zzbj, (Object) null);
        interfaceC2296d.add(zzbk, (Object) null);
        interfaceC2296d.add(zzbl, (Object) null);
        interfaceC2296d.add(zzbm, (Object) null);
        interfaceC2296d.add(zzbn, (Object) null);
        interfaceC2296d.add(zzbo, (Object) null);
        interfaceC2296d.add(zzbp, (Object) null);
        interfaceC2296d.add(zzbq, (Object) null);
        interfaceC2296d.add(zzbr, (Object) null);
        interfaceC2296d.add(zzbs, (Object) null);
        interfaceC2296d.add(zzbt, (Object) null);
        interfaceC2296d.add(zzbu, (Object) null);
        interfaceC2296d.add(zzbv, (Object) null);
        interfaceC2296d.add(zzbw, (Object) null);
        interfaceC2296d.add(zzbx, (Object) null);
        interfaceC2296d.add(zzby, (Object) null);
    }
}
