package W4;

import android.R;

/* JADX INFO: loaded from: classes3.dex */
public abstract class c {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final int[] f6292a = {R.attr.text, R.attr.hint, R.attr.maxLines, R.attr.inputType, R.attr.imeOptions, com.paymaya.R.attr.cilErrorStateBackground, com.paymaya.R.attr.cilErrorTextColor, com.paymaya.R.attr.cilHelperErrorAppearance, com.paymaya.R.attr.cilHelperNormalAppearance, com.paymaya.R.attr.cilHelperText, com.paymaya.R.attr.cilHelperTextColor, com.paymaya.R.attr.cilHintTextColor, com.paymaya.R.attr.cilInputAppearance, com.paymaya.R.attr.cilInputOffsetLeft, com.paymaya.R.attr.cilInputOffsetRight, com.paymaya.R.attr.cilInputTextColor, com.paymaya.R.attr.cilLabel, com.paymaya.R.attr.cilLabelAppearance, com.paymaya.R.attr.cilLabelTextColor, com.paymaya.R.attr.cilNormalStateBackground, com.paymaya.R.attr.cilShowHelper, com.paymaya.R.attr.cilShowLabel};

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    public static final int[] f6293b = {com.paymaya.R.attr.htmlUnderline};
    public static final int[] c = {com.paymaya.R.attr.kibvBaseText, com.paymaya.R.attr.kibvHighlightSpan};

    /* JADX INFO: renamed from: d, reason: collision with root package name */
    public static final int[] f6294d = {R.attr.enabled, R.attr.text, R.attr.hint, com.paymaya.R.attr.kddAutoHideError, com.paymaya.R.attr.kddAutoHideWarning, com.paymaya.R.attr.kddBackground, com.paymaya.R.attr.kddDisplayTextAppearance, com.paymaya.R.attr.kddDisplayTextColor, com.paymaya.R.attr.kddDropdownIcon, com.paymaya.R.attr.kddErrorAppearance, com.paymaya.R.attr.kddErrorBackground, com.paymaya.R.attr.kddErrorIcon, com.paymaya.R.attr.kddErrorText, com.paymaya.R.attr.kddErrorTextColor, com.paymaya.R.attr.kddHintTextAppearance, com.paymaya.R.attr.kddHintTextColor, com.paymaya.R.attr.kddLabel, com.paymaya.R.attr.kddLabelAppearance, com.paymaya.R.attr.kddLabelTextColor, com.paymaya.R.attr.kddShowDropdownIcon, com.paymaya.R.attr.kddShowError, com.paymaya.R.attr.kddShowErrorIcon, com.paymaya.R.attr.kddShowLabel, com.paymaya.R.attr.kddShowWarning, com.paymaya.R.attr.kddShowWarningIcon, com.paymaya.R.attr.kddWarningAppearance, com.paymaya.R.attr.kddWarningIcon, com.paymaya.R.attr.kddWarningText, com.paymaya.R.attr.kddWarningTextColor};
    public static final int[] e = {com.paymaya.R.attr.kisBackground, com.paymaya.R.attr.kisDescriptionText, com.paymaya.R.attr.kisDescriptionTextAppearance, com.paymaya.R.attr.kisDescriptionTextColor, com.paymaya.R.attr.kisHeaderText, com.paymaya.R.attr.kisHeaderTextAppearance, com.paymaya.R.attr.kisHeaderTextColor, com.paymaya.R.attr.kisIsClickable, com.paymaya.R.attr.kisPadding};
    public static final int[] f = {R.attr.enabled, R.attr.text, R.attr.hint, R.attr.maxLines, R.attr.maxLength, R.attr.inputType, R.attr.imeOptions, com.paymaya.R.attr.kilAutoHideError, com.paymaya.R.attr.kilBackground, com.paymaya.R.attr.kilDisableCopyPaste, com.paymaya.R.attr.kilErrorAppearance, com.paymaya.R.attr.kilErrorBackground, com.paymaya.R.attr.kilErrorIcon, com.paymaya.R.attr.kilErrorText, com.paymaya.R.attr.kilErrorTextColor, com.paymaya.R.attr.kilHintTextAppearance, com.paymaya.R.attr.kilHintTextColor, com.paymaya.R.attr.kilInputTextAppearance, com.paymaya.R.attr.kilInputTextColor, com.paymaya.R.attr.kilLabel, com.paymaya.R.attr.kilLabelAppearance, com.paymaya.R.attr.kilLabelTextColor, com.paymaya.R.attr.kilShowError, com.paymaya.R.attr.kilShowErrorIcon, com.paymaya.R.attr.kilShowLabel};

    /* JADX INFO: renamed from: g, reason: collision with root package name */
    public static final int[] f6295g = {com.paymaya.R.attr.mbviButtonIconDrawable, com.paymaya.R.attr.mbviButtonText};
    public static final int[] h = {com.paymaya.R.attr.mccBackgroundPrimaryColor, com.paymaya.R.attr.mccBackgroundSecondaryColor, com.paymaya.R.attr.mccBottomRightImage, com.paymaya.R.attr.mccLabelText, com.paymaya.R.attr.mccPrimaryText, com.paymaya.R.attr.mccSecondaryText};
    public static final int[] i = {R.attr.enabled, R.attr.text, R.attr.hint, R.attr.maxLines, R.attr.maxLength, R.attr.inputType, R.attr.imeOptions, com.paymaya.R.attr.mddHelperErrorAppearance, com.paymaya.R.attr.mddHelperErrorText, com.paymaya.R.attr.mddHelperErrorTextColor, com.paymaya.R.attr.mddHintTextColor, com.paymaya.R.attr.mddInputAppearance, com.paymaya.R.attr.mddInputTextColor, com.paymaya.R.attr.mddLabel, com.paymaya.R.attr.mddLabelAppearance, com.paymaya.R.attr.mddLabelErrorAppearance, com.paymaya.R.attr.mddLabelTextColor, com.paymaya.R.attr.mddPrimaryIconDrawable, com.paymaya.R.attr.mddShowHelperError};
    public static final int[] j = {com.paymaya.R.attr.expandableCollapsedIcon, com.paymaya.R.attr.expandableContent, com.paymaya.R.attr.expandableExpandedIcon, com.paymaya.R.attr.expandableIconPadding, com.paymaya.R.attr.expandableIconPaddingBottom, com.paymaya.R.attr.expandableIconPaddingEnd, com.paymaya.R.attr.expandableIconPaddingStart, com.paymaya.R.attr.expandableIconPaddingTop, com.paymaya.R.attr.expandableIconTint, com.paymaya.R.attr.titlePadding, com.paymaya.R.attr.titlePaddingBottom, com.paymaya.R.attr.titlePaddingEnd, com.paymaya.R.attr.titlePaddingStart, com.paymaya.R.attr.titlePaddingTop, com.paymaya.R.attr.titleText, com.paymaya.R.attr.titleTextAppearance, com.paymaya.R.attr.titleTwoPadding, com.paymaya.R.attr.titleTwoPaddingBottom, com.paymaya.R.attr.titleTwoPaddingEnd, com.paymaya.R.attr.titleTwoPaddingStart, com.paymaya.R.attr.titleTwoPaddingTop, com.paymaya.R.attr.titleTwoText, com.paymaya.R.attr.titleTwoTextAppearance};

    /* JADX INFO: renamed from: k, reason: collision with root package name */
    public static final int[] f6296k = {com.paymaya.R.attr.mhlIconDrawable, com.paymaya.R.attr.mhlLabelText};

    /* JADX INFO: renamed from: l, reason: collision with root package name */
    public static final int[] f6297l = {R.attr.enabled, R.attr.text, R.attr.hint, R.attr.maxLines, R.attr.maxLength, R.attr.inputType, R.attr.imeOptions, com.paymaya.R.attr.milCloseButtonDrawable, com.paymaya.R.attr.milDisableStateBackground, com.paymaya.R.attr.milErrorStateBackground, com.paymaya.R.attr.milHelperErrorAppearance, com.paymaya.R.attr.milHelperErrorIconDrawable, com.paymaya.R.attr.milHelperErrorText, com.paymaya.R.attr.milHelperErrorTextColor, com.paymaya.R.attr.milHelperInfoAppearance, com.paymaya.R.attr.milHelperInfoIconDrawable, com.paymaya.R.attr.milHelperInfoText, com.paymaya.R.attr.milHelperInfoTextColor, com.paymaya.R.attr.milHintTextColor, com.paymaya.R.attr.milInputAppearance, com.paymaya.R.attr.milInputCopyPasteEnabled, com.paymaya.R.attr.milInputOffsetLeft, com.paymaya.R.attr.milInputOffsetRight, com.paymaya.R.attr.milInputTextColor, com.paymaya.R.attr.milLabel, com.paymaya.R.attr.milLabelAppearance, com.paymaya.R.attr.milLabelErrorAppearance, com.paymaya.R.attr.milLabelTextColor, com.paymaya.R.attr.milNormalStateBackground, com.paymaya.R.attr.milPrimaryIconDrawable, com.paymaya.R.attr.milSecondaryIconDrawable, com.paymaya.R.attr.milShowCloseIcon, com.paymaya.R.attr.milShowFloatingPrefix, com.paymaya.R.attr.milShowHelperError, com.paymaya.R.attr.milShowHelperInfo, com.paymaya.R.attr.milShowLabel, com.paymaya.R.attr.milShowPrimaryIcon, com.paymaya.R.attr.milShowSecondaryIcon, com.paymaya.R.attr.milShowSubLabel, com.paymaya.R.attr.milSubLabelText};
    public static final int[] m = {com.paymaya.R.attr.msmvBaseText, com.paymaya.R.attr.msmvBaseTextColor, com.paymaya.R.attr.msmvErrorText, com.paymaya.R.attr.msmvErrorTextColor, com.paymaya.R.attr.msmvSideMargin, com.paymaya.R.attr.msmvTextSize};

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    public static final int[] f6298n = {com.paymaya.R.attr.mrtlSelectedPadding, com.paymaya.R.attr.mrtlTabInnerMargin, com.paymaya.R.attr.mrtlTabOuterMargin, com.paymaya.R.attr.mrtlUnselectedPadding};

    /* JADX INFO: renamed from: o, reason: collision with root package name */
    public static final int[] f6299o = {com.paymaya.R.attr.rirvItemDividerLength};

    /* JADX INFO: renamed from: p, reason: collision with root package name */
    public static final int[] f6300p = {com.paymaya.R.attr.msifsIndexItemDefaultAppearance, com.paymaya.R.attr.msifsIndexItemHorizontalPadding, com.paymaya.R.attr.msifsIndexItemSelectedAppearance, com.paymaya.R.attr.msifsIndexItemVerticalPadding, com.paymaya.R.attr.msifsIndexPopupBackground, com.paymaya.R.attr.msifsIndexPopupHeight, com.paymaya.R.attr.msifsIndexPopupLeftPadding, com.paymaya.R.attr.msifsIndexPopupOffsetFromList, com.paymaya.R.attr.msifsIndexPopupRightPadding, com.paymaya.R.attr.msifsIndexPopupTextAppearance, com.paymaya.R.attr.msifsIndexPopupWidth};

    /* JADX INFO: renamed from: q, reason: collision with root package name */
    public static final int[] f6301q = {com.paymaya.R.attr.mayaColorTextPrimary, com.paymaya.R.attr.mayaColorTextSecondary, com.paymaya.R.attr.meterAnimationDuration, com.paymaya.R.attr.meterBackgroundColor, com.paymaya.R.attr.meterCornerRadius, com.paymaya.R.attr.meterCurrentValue, com.paymaya.R.attr.meterLineLength, com.paymaya.R.attr.meterLineSpacing, com.paymaya.R.attr.meterLineThickness, com.paymaya.R.attr.meterMarkerHeight, com.paymaya.R.attr.meterMaxValue, com.paymaya.R.attr.meterMinValue, com.paymaya.R.attr.meterPaddingHorizontal, com.paymaya.R.attr.meterPaddingVertical, com.paymaya.R.attr.meterProgressColor, com.paymaya.R.attr.meterSegmentWidthMultiplier, com.paymaya.R.attr.meterTextColor, com.paymaya.R.attr.meterTierLabelTextSize, com.paymaya.R.attr.meterTierTextColor, com.paymaya.R.attr.meterTierTextSize, com.paymaya.R.attr.meterTrackColor, com.paymaya.R.attr.meterTrackHeight, com.paymaya.R.attr.meterValueIndicatorSize, com.paymaya.R.attr.meterValueIndicatorSpacing, com.paymaya.R.attr.meterValueTextColor, com.paymaya.R.attr.meterValueTextSize};

    /* JADX INFO: renamed from: r, reason: collision with root package name */
    public static final int[] f6302r = {com.paymaya.R.attr.mctvSecondaryIndexListHighlight, com.paymaya.R.attr.mctvSecondaryTextColor, com.paymaya.R.attr.mctvSecondaryTextHighlightSpan};

    /* JADX INFO: renamed from: s, reason: collision with root package name */
    public static final int[] f6303s = {com.paymaya.R.attr.savBackgroundView, com.paymaya.R.attr.savForegroundView, com.paymaya.R.attr.savLoadExpandingDuration, com.paymaya.R.attr.savLoadFinishingDuration, com.paymaya.R.attr.savLoadInProgressTint, com.paymaya.R.attr.savLoadProgressBarWidth, com.paymaya.R.attr.savResettingDuration, com.paymaya.R.attr.savShouldFadeForegroundOnSlide, com.paymaya.R.attr.savSlideAutoCompleteEnabled, com.paymaya.R.attr.savSlideAutoCompleteThreshold, com.paymaya.R.attr.savSlideAutoCompletingDuration, com.paymaya.R.attr.savSlideBackDuration, com.paymaya.R.attr.savSliderBackgroundDrawable, com.paymaya.R.attr.savSliderForwardIcon, com.paymaya.R.attr.savSliderLoadFinishedIcon, com.paymaya.R.attr.savSliderWidth};

    /* JADX INFO: renamed from: t, reason: collision with root package name */
    public static final int[] f6304t = {com.paymaya.R.attr.initialStep, com.paymaya.R.attr.progressColor, com.paymaya.R.attr.remainingColor, com.paymaya.R.attr.steps};

    /* JADX INFO: renamed from: u, reason: collision with root package name */
    public static final int[] f6305u = {com.paymaya.R.attr.tvwiTextAlignment, com.paymaya.R.attr.tvwiUseLineHeight};
}
