package com.google.android.gms.internal.mlkit_vision_common;

import androidx.media3.datasource.cache.c;
import com.google.android.gms.internal.ads.AbstractC1173g;
import java.io.IOException;
import java.util.HashMap;
import u2.C2294b;
import u2.InterfaceC2295c;
import u2.InterfaceC2296d;

/* JADX INFO: loaded from: classes3.dex */
final class zzeo implements InterfaceC2295c {
    private static final C2294b zzA;
    private static final C2294b zzB;
    private static final C2294b zzC;
    private static final C2294b zzD;
    private static final C2294b zzE;
    private static final C2294b zzF;
    private static final C2294b zzG;
    private static final C2294b zzH;
    private static final C2294b zzI;
    private static final C2294b zzJ;
    private static final C2294b zzK;
    private static final C2294b zzL;
    private static final C2294b zzM;
    private static final C2294b zzN;
    private static final C2294b zzO;
    private static final C2294b zzP;
    private static final C2294b zzQ;
    private static final C2294b zzR;
    private static final C2294b zzS;
    private static final C2294b zzT;
    private static final C2294b zzU;
    private static final C2294b zzV;
    private static final C2294b zzW;
    private static final C2294b zzX;
    private static final C2294b zzY;
    private static final C2294b zzZ;
    static final zzeo zza = new zzeo();
    private static final C2294b zzaA;
    private static final C2294b zzaB;
    private static final C2294b zzaC;
    private static final C2294b zzaD;
    private static final C2294b zzaE;
    private static final C2294b zzaF;
    private static final C2294b zzaG;
    private static final C2294b zzaH;
    private static final C2294b zzaI;
    private static final C2294b zzaJ;
    private static final C2294b zzaK;
    private static final C2294b zzaL;
    private static final C2294b zzaM;
    private static final C2294b zzaa;
    private static final C2294b zzab;
    private static final C2294b zzac;
    private static final C2294b zzad;
    private static final C2294b zzae;
    private static final C2294b zzaf;
    private static final C2294b zzag;
    private static final C2294b zzah;
    private static final C2294b zzai;
    private static final C2294b zzaj;
    private static final C2294b zzak;
    private static final C2294b zzal;
    private static final C2294b zzam;
    private static final C2294b zzan;
    private static final C2294b zzao;
    private static final C2294b zzap;
    private static final C2294b zzaq;
    private static final C2294b zzar;
    private static final C2294b zzas;
    private static final C2294b zzat;
    private static final C2294b zzau;
    private static final C2294b zzav;
    private static final C2294b zzaw;
    private static final C2294b zzax;
    private static final C2294b zzay;
    private static final C2294b zzaz;
    private static final C2294b zzb;
    private static final C2294b zzc;
    private static final C2294b zzd;
    private static final C2294b zze;
    private static final C2294b zzf;
    private static final C2294b zzg;
    private static final C2294b zzh;
    private static final C2294b zzi;
    private static final C2294b zzj;
    private static final C2294b zzk;
    private static final C2294b zzl;
    private static final C2294b zzm;
    private static final C2294b zzn;
    private static final C2294b zzo;
    private static final C2294b zzp;
    private static final C2294b zzq;
    private static final C2294b zzr;
    private static final C2294b zzs;
    private static final C2294b zzt;
    private static final C2294b zzu;
    private static final C2294b zzv;
    private static final C2294b zzw;
    private static final C2294b zzx;
    private static final C2294b zzy;
    private static final C2294b zzz;

    static {
        zzai zzaiVarK = AbstractC1173g.k(1);
        HashMap map = new HashMap();
        map.put(zzaiVarK.annotationType(), zzaiVarK);
        zzb = new C2294b("systemInfo", c.r(map));
        zzai zzaiVarK2 = AbstractC1173g.k(2);
        HashMap map2 = new HashMap();
        map2.put(zzaiVarK2.annotationType(), zzaiVarK2);
        zzc = new C2294b("eventName", c.r(map2));
        zzai zzaiVarK3 = AbstractC1173g.k(37);
        HashMap map3 = new HashMap();
        map3.put(zzaiVarK3.annotationType(), zzaiVarK3);
        zzd = new C2294b("isThickClient", c.r(map3));
        zzai zzaiVarK4 = AbstractC1173g.k(61);
        HashMap map4 = new HashMap();
        map4.put(zzaiVarK4.annotationType(), zzaiVarK4);
        zze = new C2294b("clientType", c.r(map4));
        zzai zzaiVarK5 = AbstractC1173g.k(3);
        HashMap map5 = new HashMap();
        map5.put(zzaiVarK5.annotationType(), zzaiVarK5);
        zzf = new C2294b("modelDownloadLogEvent", c.r(map5));
        zzai zzaiVarK6 = AbstractC1173g.k(20);
        HashMap map6 = new HashMap();
        map6.put(zzaiVarK6.annotationType(), zzaiVarK6);
        zzg = new C2294b("customModelLoadLogEvent", c.r(map6));
        zzai zzaiVarK7 = AbstractC1173g.k(4);
        HashMap map7 = new HashMap();
        map7.put(zzaiVarK7.annotationType(), zzaiVarK7);
        zzh = new C2294b("customModelInferenceLogEvent", c.r(map7));
        zzai zzaiVarK8 = AbstractC1173g.k(29);
        HashMap map8 = new HashMap();
        map8.put(zzaiVarK8.annotationType(), zzaiVarK8);
        zzi = new C2294b("customModelCreateLogEvent", c.r(map8));
        zzai zzaiVarK9 = AbstractC1173g.k(5);
        HashMap map9 = new HashMap();
        map9.put(zzaiVarK9.annotationType(), zzaiVarK9);
        zzj = new C2294b("onDeviceFaceDetectionLogEvent", c.r(map9));
        zzai zzaiVarK10 = AbstractC1173g.k(59);
        HashMap map10 = new HashMap();
        map10.put(zzaiVarK10.annotationType(), zzaiVarK10);
        zzk = new C2294b("onDeviceFaceLoadLogEvent", c.r(map10));
        zzai zzaiVarK11 = AbstractC1173g.k(6);
        HashMap map11 = new HashMap();
        map11.put(zzaiVarK11.annotationType(), zzaiVarK11);
        zzl = new C2294b("onDeviceTextDetectionLogEvent", c.r(map11));
        zzai zzaiVarK12 = AbstractC1173g.k(79);
        HashMap map12 = new HashMap();
        map12.put(zzaiVarK12.annotationType(), zzaiVarK12);
        zzm = new C2294b("onDeviceTextDetectionLoadLogEvent", c.r(map12));
        zzai zzaiVarK13 = AbstractC1173g.k(7);
        HashMap map13 = new HashMap();
        map13.put(zzaiVarK13.annotationType(), zzaiVarK13);
        zzn = new C2294b("onDeviceBarcodeDetectionLogEvent", c.r(map13));
        zzai zzaiVarK14 = AbstractC1173g.k(58);
        HashMap map14 = new HashMap();
        map14.put(zzaiVarK14.annotationType(), zzaiVarK14);
        zzo = new C2294b("onDeviceBarcodeLoadLogEvent", c.r(map14));
        zzai zzaiVarK15 = AbstractC1173g.k(48);
        HashMap map15 = new HashMap();
        map15.put(zzaiVarK15.annotationType(), zzaiVarK15);
        zzp = new C2294b("onDeviceImageLabelCreateLogEvent", c.r(map15));
        zzai zzaiVarK16 = AbstractC1173g.k(49);
        HashMap map16 = new HashMap();
        map16.put(zzaiVarK16.annotationType(), zzaiVarK16);
        zzq = new C2294b("onDeviceImageLabelLoadLogEvent", c.r(map16));
        zzai zzaiVarK17 = AbstractC1173g.k(18);
        HashMap map17 = new HashMap();
        map17.put(zzaiVarK17.annotationType(), zzaiVarK17);
        zzr = new C2294b("onDeviceImageLabelDetectionLogEvent", c.r(map17));
        zzai zzaiVarK18 = AbstractC1173g.k(26);
        HashMap map18 = new HashMap();
        map18.put(zzaiVarK18.annotationType(), zzaiVarK18);
        zzs = new C2294b("onDeviceObjectCreateLogEvent", c.r(map18));
        zzai zzaiVarK19 = AbstractC1173g.k(27);
        HashMap map19 = new HashMap();
        map19.put(zzaiVarK19.annotationType(), zzaiVarK19);
        zzt = new C2294b("onDeviceObjectLoadLogEvent", c.r(map19));
        zzai zzaiVarK20 = AbstractC1173g.k(28);
        HashMap map20 = new HashMap();
        map20.put(zzaiVarK20.annotationType(), zzaiVarK20);
        zzu = new C2294b("onDeviceObjectInferenceLogEvent", c.r(map20));
        zzai zzaiVarK21 = AbstractC1173g.k(44);
        HashMap map21 = new HashMap();
        map21.put(zzaiVarK21.annotationType(), zzaiVarK21);
        zzv = new C2294b("onDevicePoseDetectionLogEvent", c.r(map21));
        zzai zzaiVarK22 = AbstractC1173g.k(45);
        HashMap map22 = new HashMap();
        map22.put(zzaiVarK22.annotationType(), zzaiVarK22);
        zzw = new C2294b("onDeviceSegmentationLogEvent", c.r(map22));
        zzai zzaiVarK23 = AbstractC1173g.k(19);
        HashMap map23 = new HashMap();
        map23.put(zzaiVarK23.annotationType(), zzaiVarK23);
        zzx = new C2294b("onDeviceSmartReplyLogEvent", c.r(map23));
        zzai zzaiVarK24 = AbstractC1173g.k(21);
        HashMap map24 = new HashMap();
        map24.put(zzaiVarK24.annotationType(), zzaiVarK24);
        zzy = new C2294b("onDeviceLanguageIdentificationLogEvent", c.r(map24));
        zzai zzaiVarK25 = AbstractC1173g.k(22);
        HashMap map25 = new HashMap();
        map25.put(zzaiVarK25.annotationType(), zzaiVarK25);
        zzz = new C2294b("onDeviceTranslationLogEvent", c.r(map25));
        zzai zzaiVarK26 = AbstractC1173g.k(8);
        HashMap map26 = new HashMap();
        map26.put(zzaiVarK26.annotationType(), zzaiVarK26);
        zzA = new C2294b("cloudFaceDetectionLogEvent", c.r(map26));
        zzai zzaiVarK27 = AbstractC1173g.k(9);
        HashMap map27 = new HashMap();
        map27.put(zzaiVarK27.annotationType(), zzaiVarK27);
        zzB = new C2294b("cloudCropHintDetectionLogEvent", c.r(map27));
        zzai zzaiVarK28 = AbstractC1173g.k(10);
        HashMap map28 = new HashMap();
        map28.put(zzaiVarK28.annotationType(), zzaiVarK28);
        zzC = new C2294b("cloudDocumentTextDetectionLogEvent", c.r(map28));
        zzai zzaiVarK29 = AbstractC1173g.k(11);
        HashMap map29 = new HashMap();
        map29.put(zzaiVarK29.annotationType(), zzaiVarK29);
        zzD = new C2294b("cloudImagePropertiesDetectionLogEvent", c.r(map29));
        zzai zzaiVarK30 = AbstractC1173g.k(12);
        HashMap map30 = new HashMap();
        map30.put(zzaiVarK30.annotationType(), zzaiVarK30);
        zzE = new C2294b("cloudImageLabelDetectionLogEvent", c.r(map30));
        zzai zzaiVarK31 = AbstractC1173g.k(13);
        HashMap map31 = new HashMap();
        map31.put(zzaiVarK31.annotationType(), zzaiVarK31);
        zzF = new C2294b("cloudLandmarkDetectionLogEvent", c.r(map31));
        zzai zzaiVarK32 = AbstractC1173g.k(14);
        HashMap map32 = new HashMap();
        map32.put(zzaiVarK32.annotationType(), zzaiVarK32);
        zzG = new C2294b("cloudLogoDetectionLogEvent", c.r(map32));
        zzai zzaiVarK33 = AbstractC1173g.k(15);
        HashMap map33 = new HashMap();
        map33.put(zzaiVarK33.annotationType(), zzaiVarK33);
        zzH = new C2294b("cloudSafeSearchDetectionLogEvent", c.r(map33));
        zzai zzaiVarK34 = AbstractC1173g.k(16);
        HashMap map34 = new HashMap();
        map34.put(zzaiVarK34.annotationType(), zzaiVarK34);
        zzI = new C2294b("cloudTextDetectionLogEvent", c.r(map34));
        zzai zzaiVarK35 = AbstractC1173g.k(17);
        HashMap map35 = new HashMap();
        map35.put(zzaiVarK35.annotationType(), zzaiVarK35);
        zzJ = new C2294b("cloudWebSearchDetectionLogEvent", c.r(map35));
        zzai zzaiVarK36 = AbstractC1173g.k(23);
        HashMap map36 = new HashMap();
        map36.put(zzaiVarK36.annotationType(), zzaiVarK36);
        zzK = new C2294b("automlImageLabelingCreateLogEvent", c.r(map36));
        zzai zzaiVarK37 = AbstractC1173g.k(24);
        HashMap map37 = new HashMap();
        map37.put(zzaiVarK37.annotationType(), zzaiVarK37);
        zzL = new C2294b("automlImageLabelingLoadLogEvent", c.r(map37));
        zzai zzaiVarK38 = AbstractC1173g.k(25);
        HashMap map38 = new HashMap();
        map38.put(zzaiVarK38.annotationType(), zzaiVarK38);
        zzM = new C2294b("automlImageLabelingInferenceLogEvent", c.r(map38));
        zzai zzaiVarK39 = AbstractC1173g.k(39);
        HashMap map39 = new HashMap();
        map39.put(zzaiVarK39.annotationType(), zzaiVarK39);
        zzN = new C2294b("isModelDownloadedLogEvent", c.r(map39));
        zzai zzaiVarK40 = AbstractC1173g.k(40);
        HashMap map40 = new HashMap();
        map40.put(zzaiVarK40.annotationType(), zzaiVarK40);
        zzO = new C2294b("deleteModelLogEvent", c.r(map40));
        zzai zzaiVarK41 = AbstractC1173g.k(30);
        HashMap map41 = new HashMap();
        map41.put(zzaiVarK41.annotationType(), zzaiVarK41);
        zzP = new C2294b("aggregatedAutomlImageLabelingInferenceLogEvent", c.r(map41));
        zzai zzaiVarK42 = AbstractC1173g.k(31);
        HashMap map42 = new HashMap();
        map42.put(zzaiVarK42.annotationType(), zzaiVarK42);
        zzQ = new C2294b("aggregatedCustomModelInferenceLogEvent", c.r(map42));
        zzai zzaiVarK43 = AbstractC1173g.k(32);
        HashMap map43 = new HashMap();
        map43.put(zzaiVarK43.annotationType(), zzaiVarK43);
        zzR = new C2294b("aggregatedOnDeviceFaceDetectionLogEvent", c.r(map43));
        zzai zzaiVarK44 = AbstractC1173g.k(33);
        HashMap map44 = new HashMap();
        map44.put(zzaiVarK44.annotationType(), zzaiVarK44);
        zzS = new C2294b("aggregatedOnDeviceBarcodeDetectionLogEvent", c.r(map44));
        zzai zzaiVarK45 = AbstractC1173g.k(34);
        HashMap map45 = new HashMap();
        map45.put(zzaiVarK45.annotationType(), zzaiVarK45);
        zzT = new C2294b("aggregatedOnDeviceImageLabelDetectionLogEvent", c.r(map45));
        zzai zzaiVarK46 = AbstractC1173g.k(35);
        HashMap map46 = new HashMap();
        map46.put(zzaiVarK46.annotationType(), zzaiVarK46);
        zzU = new C2294b("aggregatedOnDeviceObjectInferenceLogEvent", c.r(map46));
        zzai zzaiVarK47 = AbstractC1173g.k(36);
        HashMap map47 = new HashMap();
        map47.put(zzaiVarK47.annotationType(), zzaiVarK47);
        zzV = new C2294b("aggregatedOnDeviceTextDetectionLogEvent", c.r(map47));
        zzai zzaiVarK48 = AbstractC1173g.k(46);
        HashMap map48 = new HashMap();
        map48.put(zzaiVarK48.annotationType(), zzaiVarK48);
        zzW = new C2294b("aggregatedOnDevicePoseDetectionLogEvent", c.r(map48));
        zzai zzaiVarK49 = AbstractC1173g.k(47);
        HashMap map49 = new HashMap();
        map49.put(zzaiVarK49.annotationType(), zzaiVarK49);
        zzX = new C2294b("aggregatedOnDeviceSegmentationLogEvent", c.r(map49));
        zzai zzaiVarK50 = AbstractC1173g.k(69);
        HashMap map50 = new HashMap();
        map50.put(zzaiVarK50.annotationType(), zzaiVarK50);
        zzY = new C2294b("pipelineAccelerationInferenceEvents", c.r(map50));
        zzai zzaiVarK51 = AbstractC1173g.k(42);
        HashMap map51 = new HashMap();
        map51.put(zzaiVarK51.annotationType(), zzaiVarK51);
        zzZ = new C2294b("remoteConfigLogEvent", c.r(map51));
        zzai zzaiVarK52 = AbstractC1173g.k(50);
        HashMap map52 = new HashMap();
        map52.put(zzaiVarK52.annotationType(), zzaiVarK52);
        zzaa = new C2294b("inputImageConstructionLogEvent", c.r(map52));
        zzai zzaiVarK53 = AbstractC1173g.k(51);
        HashMap map53 = new HashMap();
        map53.put(zzaiVarK53.annotationType(), zzaiVarK53);
        zzab = new C2294b("leakedHandleEvent", c.r(map53));
        zzai zzaiVarK54 = AbstractC1173g.k(52);
        HashMap map54 = new HashMap();
        map54.put(zzaiVarK54.annotationType(), zzaiVarK54);
        zzac = new C2294b("cameraSourceLogEvent", c.r(map54));
        zzai zzaiVarK55 = AbstractC1173g.k(53);
        HashMap map55 = new HashMap();
        map55.put(zzaiVarK55.annotationType(), zzaiVarK55);
        zzad = new C2294b("imageLabelOptionalModuleLogEvent", c.r(map55));
        zzai zzaiVarK56 = AbstractC1173g.k(54);
        HashMap map56 = new HashMap();
        map56.put(zzaiVarK56.annotationType(), zzaiVarK56);
        zzae = new C2294b("languageIdentificationOptionalModuleLogEvent", c.r(map56));
        zzai zzaiVarK57 = AbstractC1173g.k(60);
        HashMap map57 = new HashMap();
        map57.put(zzaiVarK57.annotationType(), zzaiVarK57);
        zzaf = new C2294b("faceDetectionOptionalModuleLogEvent", c.r(map57));
        zzai zzaiVarK58 = AbstractC1173g.k(85);
        HashMap map58 = new HashMap();
        map58.put(zzaiVarK58.annotationType(), zzaiVarK58);
        zzag = new C2294b("documentDetectionOptionalModuleLogEvent", c.r(map58));
        zzai zzaiVarK59 = AbstractC1173g.k(86);
        HashMap map59 = new HashMap();
        map59.put(zzaiVarK59.annotationType(), zzaiVarK59);
        zzah = new C2294b("documentCroppingOptionalModuleLogEvent", c.r(map59));
        zzai zzaiVarK60 = AbstractC1173g.k(87);
        HashMap map60 = new HashMap();
        map60.put(zzaiVarK60.annotationType(), zzaiVarK60);
        zzai = new C2294b("documentEnhancementOptionalModuleLogEvent", c.r(map60));
        zzai zzaiVarK61 = AbstractC1173g.k(55);
        HashMap map61 = new HashMap();
        map61.put(zzaiVarK61.annotationType(), zzaiVarK61);
        zzaj = new C2294b("nlClassifierOptionalModuleLogEvent", c.r(map61));
        zzai zzaiVarK62 = AbstractC1173g.k(56);
        HashMap map62 = new HashMap();
        map62.put(zzaiVarK62.annotationType(), zzaiVarK62);
        zzak = new C2294b("nlClassifierClientLibraryLogEvent", c.r(map62));
        zzai zzaiVarK63 = AbstractC1173g.k(57);
        HashMap map63 = new HashMap();
        map63.put(zzaiVarK63.annotationType(), zzaiVarK63);
        zzal = new C2294b("accelerationAllowlistLogEvent", c.r(map63));
        zzai zzaiVarK64 = AbstractC1173g.k(62);
        HashMap map64 = new HashMap();
        map64.put(zzaiVarK64.annotationType(), zzaiVarK64);
        zzam = new C2294b("toxicityDetectionCreateEvent", c.r(map64));
        zzai zzaiVarK65 = AbstractC1173g.k(63);
        HashMap map65 = new HashMap();
        map65.put(zzaiVarK65.annotationType(), zzaiVarK65);
        zzan = new C2294b("toxicityDetectionLoadEvent", c.r(map65));
        zzai zzaiVarK66 = AbstractC1173g.k(64);
        HashMap map66 = new HashMap();
        map66.put(zzaiVarK66.annotationType(), zzaiVarK66);
        zzao = new C2294b("toxicityDetectionInferenceEvent", c.r(map66));
        zzai zzaiVarK67 = AbstractC1173g.k(65);
        HashMap map67 = new HashMap();
        map67.put(zzaiVarK67.annotationType(), zzaiVarK67);
        zzap = new C2294b("barcodeDetectionOptionalModuleLogEvent", c.r(map67));
        zzai zzaiVarK68 = AbstractC1173g.k(66);
        HashMap map68 = new HashMap();
        map68.put(zzaiVarK68.annotationType(), zzaiVarK68);
        zzaq = new C2294b("customImageLabelOptionalModuleLogEvent", c.r(map68));
        zzai zzaiVarK69 = AbstractC1173g.k(67);
        HashMap map69 = new HashMap();
        map69.put(zzaiVarK69.annotationType(), zzaiVarK69);
        zzar = new C2294b("codeScannerScanApiEvent", c.r(map69));
        zzai zzaiVarK70 = AbstractC1173g.k(68);
        HashMap map70 = new HashMap();
        map70.put(zzaiVarK70.annotationType(), zzaiVarK70);
        zzas = new C2294b("codeScannerOptionalModuleEvent", c.r(map70));
        zzai zzaiVarK71 = AbstractC1173g.k(70);
        HashMap map71 = new HashMap();
        map71.put(zzaiVarK71.annotationType(), zzaiVarK71);
        zzat = new C2294b("onDeviceExplicitContentCreateLogEvent", c.r(map71));
        zzai zzaiVarK72 = AbstractC1173g.k(71);
        HashMap map72 = new HashMap();
        map72.put(zzaiVarK72.annotationType(), zzaiVarK72);
        zzau = new C2294b("onDeviceExplicitContentLoadLogEvent", c.r(map72));
        zzai zzaiVarK73 = AbstractC1173g.k(72);
        HashMap map73 = new HashMap();
        map73.put(zzaiVarK73.annotationType(), zzaiVarK73);
        zzav = new C2294b("onDeviceExplicitContentInferenceLogEvent", c.r(map73));
        zzai zzaiVarK74 = AbstractC1173g.k(73);
        HashMap map74 = new HashMap();
        map74.put(zzaiVarK74.annotationType(), zzaiVarK74);
        zzaw = new C2294b("aggregatedOnDeviceExplicitContentLogEvent", c.r(map74));
        zzai zzaiVarK75 = AbstractC1173g.k(74);
        HashMap map75 = new HashMap();
        map75.put(zzaiVarK75.annotationType(), zzaiVarK75);
        zzax = new C2294b("onDeviceFaceMeshCreateLogEvent", c.r(map75));
        zzai zzaiVarK76 = AbstractC1173g.k(75);
        HashMap map76 = new HashMap();
        map76.put(zzaiVarK76.annotationType(), zzaiVarK76);
        zzay = new C2294b("onDeviceFaceMeshLoadLogEvent", c.r(map76));
        zzai zzaiVarK77 = AbstractC1173g.k(76);
        HashMap map77 = new HashMap();
        map77.put(zzaiVarK77.annotationType(), zzaiVarK77);
        zzaz = new C2294b("onDeviceFaceMeshLogEvent", c.r(map77));
        zzai zzaiVarK78 = AbstractC1173g.k(77);
        HashMap map78 = new HashMap();
        map78.put(zzaiVarK78.annotationType(), zzaiVarK78);
        zzaA = new C2294b("aggregatedOnDeviceFaceMeshLogEvent", c.r(map78));
        zzai zzaiVarK79 = AbstractC1173g.k(78);
        HashMap map79 = new HashMap();
        map79.put(zzaiVarK79.annotationType(), zzaiVarK79);
        zzaB = new C2294b("smartReplyOptionalModuleLogEvent", c.r(map79));
        zzai zzaiVarK80 = AbstractC1173g.k(80);
        HashMap map80 = new HashMap();
        map80.put(zzaiVarK80.annotationType(), zzaiVarK80);
        zzaC = new C2294b("textDetectionOptionalModuleLogEvent", c.r(map80));
        zzai zzaiVarK81 = AbstractC1173g.k(81);
        HashMap map81 = new HashMap();
        map81.put(zzaiVarK81.annotationType(), zzaiVarK81);
        zzaD = new C2294b("onDeviceImageQualityAnalysisCreateLogEvent", c.r(map81));
        zzai zzaiVarK82 = AbstractC1173g.k(82);
        HashMap map82 = new HashMap();
        map82.put(zzaiVarK82.annotationType(), zzaiVarK82);
        zzaE = new C2294b("onDeviceImageQualityAnalysisLoadLogEvent", c.r(map82));
        zzai zzaiVarK83 = AbstractC1173g.k(83);
        HashMap map83 = new HashMap();
        map83.put(zzaiVarK83.annotationType(), zzaiVarK83);
        zzaF = new C2294b("onDeviceImageQualityAnalysisLogEvent", c.r(map83));
        zzai zzaiVarK84 = AbstractC1173g.k(84);
        HashMap map84 = new HashMap();
        map84.put(zzaiVarK84.annotationType(), zzaiVarK84);
        zzaG = new C2294b("aggregatedOnDeviceImageQualityAnalysisLogEvent", c.r(map84));
        zzai zzaiVarK85 = AbstractC1173g.k(88);
        HashMap map85 = new HashMap();
        map85.put(zzaiVarK85.annotationType(), zzaiVarK85);
        zzaH = new C2294b("imageQualityAnalysisOptionalModuleLogEvent", c.r(map85));
        zzai zzaiVarK86 = AbstractC1173g.k(89);
        HashMap map86 = new HashMap();
        map86.put(zzaiVarK86.annotationType(), zzaiVarK86);
        zzaI = new C2294b("imageCaptioningOptionalModuleLogEvent", c.r(map86));
        zzai zzaiVarK87 = AbstractC1173g.k(90);
        HashMap map87 = new HashMap();
        map87.put(zzaiVarK87.annotationType(), zzaiVarK87);
        zzaJ = new C2294b("onDeviceImageCaptioningCreateLogEvent", c.r(map87));
        zzai zzaiVarK88 = AbstractC1173g.k(91);
        HashMap map88 = new HashMap();
        map88.put(zzaiVarK88.annotationType(), zzaiVarK88);
        zzaK = new C2294b("onDeviceImageCaptioningLoadLogEvent", c.r(map88));
        zzai zzaiVarK89 = AbstractC1173g.k(92);
        HashMap map89 = new HashMap();
        map89.put(zzaiVarK89.annotationType(), zzaiVarK89);
        zzaL = new C2294b("onDeviceImageCaptioningInferenceLogEvent", c.r(map89));
        zzai zzaiVarK90 = AbstractC1173g.k(93);
        HashMap map90 = new HashMap();
        map90.put(zzaiVarK90.annotationType(), zzaiVarK90);
        zzaM = new C2294b("aggregatedOnDeviceImageCaptioningInferenceLogEvent", c.r(map90));
    }

    private zzeo() {
    }

    @Override // u2.InterfaceC2293a
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zziy zziyVar = (zziy) obj;
        InterfaceC2296d interfaceC2296d = (InterfaceC2296d) obj2;
        interfaceC2296d.add(zzb, zziyVar.zzc());
        interfaceC2296d.add(zzc, zziyVar.zzb());
        interfaceC2296d.add(zzd, (Object) null);
        interfaceC2296d.add(zze, (Object) null);
        interfaceC2296d.add(zzf, (Object) null);
        interfaceC2296d.add(zzg, (Object) null);
        interfaceC2296d.add(zzh, (Object) null);
        interfaceC2296d.add(zzi, (Object) null);
        interfaceC2296d.add(zzj, (Object) null);
        interfaceC2296d.add(zzk, (Object) null);
        interfaceC2296d.add(zzl, (Object) null);
        interfaceC2296d.add(zzm, (Object) null);
        interfaceC2296d.add(zzn, (Object) null);
        interfaceC2296d.add(zzo, (Object) null);
        interfaceC2296d.add(zzp, (Object) null);
        interfaceC2296d.add(zzq, (Object) null);
        interfaceC2296d.add(zzr, (Object) null);
        interfaceC2296d.add(zzs, (Object) null);
        interfaceC2296d.add(zzt, (Object) null);
        interfaceC2296d.add(zzu, (Object) null);
        interfaceC2296d.add(zzv, (Object) null);
        interfaceC2296d.add(zzw, (Object) null);
        interfaceC2296d.add(zzx, (Object) null);
        interfaceC2296d.add(zzy, (Object) null);
        interfaceC2296d.add(zzz, (Object) null);
        interfaceC2296d.add(zzA, (Object) null);
        interfaceC2296d.add(zzB, (Object) null);
        interfaceC2296d.add(zzC, (Object) null);
        interfaceC2296d.add(zzD, (Object) null);
        interfaceC2296d.add(zzE, (Object) null);
        interfaceC2296d.add(zzF, (Object) null);
        interfaceC2296d.add(zzG, (Object) null);
        interfaceC2296d.add(zzH, (Object) null);
        interfaceC2296d.add(zzI, (Object) null);
        interfaceC2296d.add(zzJ, (Object) null);
        interfaceC2296d.add(zzK, (Object) null);
        interfaceC2296d.add(zzL, (Object) null);
        interfaceC2296d.add(zzM, (Object) null);
        interfaceC2296d.add(zzN, (Object) null);
        interfaceC2296d.add(zzO, (Object) null);
        interfaceC2296d.add(zzP, (Object) null);
        interfaceC2296d.add(zzQ, (Object) null);
        interfaceC2296d.add(zzR, (Object) null);
        interfaceC2296d.add(zzS, (Object) null);
        interfaceC2296d.add(zzT, (Object) null);
        interfaceC2296d.add(zzU, (Object) null);
        interfaceC2296d.add(zzV, (Object) null);
        interfaceC2296d.add(zzW, (Object) null);
        interfaceC2296d.add(zzX, (Object) null);
        interfaceC2296d.add(zzY, (Object) null);
        interfaceC2296d.add(zzZ, (Object) null);
        interfaceC2296d.add(zzaa, zziyVar.zza());
        interfaceC2296d.add(zzab, (Object) null);
        interfaceC2296d.add(zzac, (Object) null);
        interfaceC2296d.add(zzad, (Object) null);
        interfaceC2296d.add(zzae, (Object) null);
        interfaceC2296d.add(zzaf, (Object) null);
        interfaceC2296d.add(zzag, (Object) null);
        interfaceC2296d.add(zzah, (Object) null);
        interfaceC2296d.add(zzai, (Object) null);
        interfaceC2296d.add(zzaj, (Object) null);
        interfaceC2296d.add(zzak, (Object) null);
        interfaceC2296d.add(zzal, (Object) null);
        interfaceC2296d.add(zzam, (Object) null);
        interfaceC2296d.add(zzan, (Object) null);
        interfaceC2296d.add(zzao, (Object) null);
        interfaceC2296d.add(zzap, (Object) null);
        interfaceC2296d.add(zzaq, (Object) null);
        interfaceC2296d.add(zzar, (Object) null);
        interfaceC2296d.add(zzas, (Object) null);
        interfaceC2296d.add(zzat, (Object) null);
        interfaceC2296d.add(zzau, (Object) null);
        interfaceC2296d.add(zzav, (Object) null);
        interfaceC2296d.add(zzaw, (Object) null);
        interfaceC2296d.add(zzax, (Object) null);
        interfaceC2296d.add(zzay, (Object) null);
        interfaceC2296d.add(zzaz, (Object) null);
        interfaceC2296d.add(zzaA, (Object) null);
        interfaceC2296d.add(zzaB, (Object) null);
        interfaceC2296d.add(zzaC, (Object) null);
        interfaceC2296d.add(zzaD, (Object) null);
        interfaceC2296d.add(zzaE, (Object) null);
        interfaceC2296d.add(zzaF, (Object) null);
        interfaceC2296d.add(zzaG, (Object) null);
        interfaceC2296d.add(zzaH, (Object) null);
        interfaceC2296d.add(zzaI, (Object) null);
        interfaceC2296d.add(zzaJ, (Object) null);
        interfaceC2296d.add(zzaK, (Object) null);
        interfaceC2296d.add(zzaL, (Object) null);
        interfaceC2296d.add(zzaM, (Object) null);
    }
}
